# Translations for static text

from flask import Blueprint

ce_bp = Blueprint('continuing_edu', __name__, url_prefix='/continuing_edu')



translations = {
    'en': {
        'university_name': 'Faculty of Medical Technology, Mahidol University',
        'short_courses_nav': 'Short Courses',
        'webinars_nav': 'Webinars',
        'contact_us_nav': 'Contact Us',
        'hero_title': 'Unlock Your Potential with Our Academic Offerings',
        'hero_subtitle': 'Explore a diverse range of short courses and insightful webinars designed to enhance your skills and knowledge.',
        'explore_courses_btn': 'Explore Short Courses',
        'discover_webinars_btn': 'Discover Webinars',
        'our_short_courses_title': 'Our Short Courses',
        'learn_more_btn': 'Learn More',
        'view_all_courses_btn': 'View All Short Courses',
        'upcoming_webinars_title': 'Upcoming Webinars',
        'register_now_btn': 'Register Now',
        'view_all_webinars_btn': 'View All Webinars',
        'cta_title': 'Ready to Advance Your Career?',
        'cta_subtitle': "Don't miss out on these valuable opportunities. Enroll in a course or register for a webinar today!",
        'get_started_btn': 'Get Started Now',
        'contact_us_title': 'Contact Us',
        'contact_us_description': 'Have questions about our short courses or webinars? Reach out to us!',
        'name_label': 'Name',
        'email_label': 'Email',
        'message_label': 'Message',
        'send_message_btn': 'Send Message',
        'footer_text': '&copy; 2025 University Academic Services. All rights reserved.',
        'privacy_policy': 'Privacy Policy',
        'terms_of_service': 'Terms of Service',
        'duration_label': 'Duration',
        'format_label': 'Format',
        'certification_label': 'Certification',
        'date_label': 'Date',
        'time_label': 'Time',
        'speaker_label': 'Speaker',
        'lang_en': 'English',
        'lang_th': 'Thai',
        'course_detail_title': 'Course Details',
        'back_to_courses_btn': 'Back to Courses',
        'webinar_detail_title': 'Webinar Details',
        'back_to_webinars_btn': 'Back to Webinars',
        'register_page_title': 'Register',
        'why_register_title': 'Why Register?',
        'register_now_btn': 'Register Now',
        'why_register_description': 'Registering helps you get the most out of our system, including:',
        'why_register_benefit_1': 'Access to exclusive courses and webinars reserved for members',
        'why_register_benefit_2': 'Receive certificates and personalized learning records',
        'why_register_benefit_3': 'Stay updated on the latest news, events, and benefits',
        'why_register_benefit_4': 'Safely save and manage your personal information',
        'why_register_benefit_5': 'Get fast support and backend services',

        'login_page_title': 'Login',
        'username_label': 'Username',
        'password_label': 'Password',
        'confirm_password_label': 'Confirm Password',
        'register_btn': 'Register',
        'login_btn': 'Login',
        'already_have_account': 'Already have an account?',
        'no_account_yet': 'Don\'t have an account yet?',
        'logout_btn': 'Logout',
        'welcome_message': 'Welcome,',
        'enroll_now_btn': 'Enroll Now',
        'register_to_enroll': 'Register or Login to Enroll',
        'member_type_label': 'Member Type',
        'mahidol_student': 'Mahidol Student',
        'grad_student': 'Grad Student',
        'staff': 'Staff',
        'personal': 'Personal',
        'other': 'Other',
        'gender_label': 'Gender',
        'age_range_label': 'Age Range',
        'country_label': 'Country',
        'full_name_th_label': 'Full Name (Thai)',
        'full_name_en_label': 'Full Name (English)',
        'instructors_label': 'Instructors',
        'agenda_label': 'Agenda',
        'location_label': 'Location',
        'registration_fee_label': 'Registration Fee',
        'price_for_you': 'Price for you',
        'i_accept': 'I accept',
        'accept_policy': 'Policy accepted',
        'accept_terms': 'Terms of Service',
        'receive_news': 'Accept Newsletter',

        # Member portal labels
        'my_registrations_page_title': 'My Registrations',
        'my_payments_page_title': 'My Payments',
        'label_event': 'Event',
        'label_type': 'Type',
        'label_registered_at': 'Registered At',
        'label_payment': 'Payment',
        'label_progress': 'Progress',
        'label_amount': 'Amount',
        'label_status': 'Status',
        'label_proof': 'Payment Proof',
        'label_started_at': 'Started',
        'label_completed_at': 'Completed',
        'label_actions': 'Actions',
        'label_member': 'Member',
        'label_none': 'None',
        'label_no_payment_record': 'No payment record',
        'label_early_bird': 'Early Bird',
        'register_for_label': 'Register for:',
        'currency_thb': 'THB',
        'event_type_course': 'Course',
        'event_type_webinar': 'Webinar',

        # Member portal messages
        'message_payments_locked': 'Payment is approved. Editing proof is locked.',
        'message_no_payments': 'You have no payments yet.',
        'message_no_registrations': 'You have no registrations yet.',
        'address_type_other_prompt': 'Please specify the address type.',
        'address_country_other_prompt': 'Please specify the country name.',
        'address_required_message': 'Please provide at least one address.',
        'register_error_generic': 'We could not complete your registration. Please try again.',
        'otp_email_missing': 'Please provide an email address to receive your OTP code.',

        # Member portal buttons
        'button_view': 'View',
        'button_submit_url': 'Submit URL',
        'button_replace_url': 'Replace URL',
        'button_upload_file': 'Upload File',
        'button_replace_file': 'Replace File',
        'button_view_invoice': 'View Invoice',
        'button_view_receipt': 'View Receipt',
        'button_pay_online': 'Pay Online',
        'button_start': 'Start',
        'button_complete': 'Complete',
        'button_view_certificate': 'View Certificate',
        'button_generate_certificate': 'Generate Certificate',
        'button_download_pdf': 'Download PDF',
        'button_back_home': 'Back to Home',
        'button_confirm_registration': 'Confirm Registration',
        'button_cancel': 'Cancel',

        # Member portal helpers
        'label_fee': 'Fee',
        'label_amount_thb': 'Amount',
        'hero_view_event': 'View Event',
        'hero_speakers_label': 'Speakers',
        'organization_label': 'Organization / Workplace',
        'organization_placeholder': 'Start typing to search or enter a new organization',
        'organization_type_label': 'Organization Type',
        'organization_type_other_placeholder': 'Specify organization type',
        'occupation_label': 'Occupation',
        'occupation_other_placeholder': 'Specify occupation',
        'addresses_section_title': 'Addresses',
        'address_add_button': 'Add Address',
        'address_type_current': 'Current Address',
        'address_type_billing': 'Billing Address',
        'address_type_other': 'Other',
        'address_label_field': 'Label (optional)',
        'address_line1_label': 'Address Line 1',
        'address_line2_label': 'Address Line 2',
        'address_city_label': 'City / District',
        'address_state_label': 'State / Province',
        'address_postal_label': 'Postal Code',
        'address_country_label': 'Country',
        'address_remove_button': 'Remove',

        # Invoice / Payment i18n
        'invoice_title': 'Invoice',
        'invoice_billed_to': 'Billed To',
        'invoice_details': 'Details',
        'invoice_no': 'Invoice No.',
        'invoice_amount': 'Amount',
        'invoice_status': 'Status',
        'invoice_created': 'Created',
        'invoice_how_to_pay': 'How to pay',
        'invoice_bank_info': 'Bank Info',
        'invoice_total_due': 'Total Due',
        'invoice_go_to_my_payments': 'Go to My Payments',
        'invoice_pay_via_qr': 'Pay via QR',
        'invoice_promptpay_id': 'PromptPay ID',
        'invoice_download_pdf': 'Download PDF',
        'invoice_pdf_unavailable': 'PDF Unavailable',
        'invoice_pay_online': 'Pay Online',

        # Email i18n
        'email_registered_for': 'You registered for',
        'email_amount': 'Amount',
        'email_status': 'Status',
        'email_pay_now_or_view_invoice': 'Pay now or view invoice:',
        'email_invoice': 'Invoice',
        'email_my_payments': 'My payments',
        'email_pay_online': 'Pay Online',
        "email_buttons_fallback": "If the buttons don't work, you can copy these links into your browser:",

        # Misc
        'not_allowed': 'You are not allowed to view this invoice.',
        'pdf_unavailable': 'PDF generation is currently unavailable.',
        'status_pending': 'pending'

    },
    'th': {
        'university_name': 'คณะเทคนิคการแพทย์ มหาวิทยาลัยมหิดล',
        'short_courses_nav': 'หลักสูตรระยะสั้น',
        'webinars_nav': 'การสัมมนาผ่านเว็บ',
        'contact_us_nav': 'ติดต่อเรา',
        'hero_title': 'ปลดล็อกศักยภาพของคุณด้วยข้อเสนอทางวิชาการของเรา',
        'hero_subtitle': 'สำรวจหลักสูตรระยะสั้นที่หลากหลายและการสัมมนาผ่านเว็บเชิงลึกที่ออกแบบมาเพื่อเพิ่มพูนทักษะและความรู้ของคุณ',
        'explore_courses_btn': 'สำรวจหลักสูตรระยะสั้น',
        'discover_webinars_btn': 'ค้นพบการสัมมนาผ่านเว็บ',
        'our_short_courses_title': 'หลักสูตรระยะสั้นของเรา',
        'learn_more_btn': 'เรียนรู้เพิ่มเติม',
        'view_all_courses_btn': 'ดูหลักสูตรระยะสั้นทั้งหมด',
        'upcoming_webinars_title': 'การสัมมนาผ่านเว็บที่กำลังจะมาถึง',
        'register_now_btn': 'ลงทะเบียนตอนนี้',
        'view_all_webinars_btn': 'ดูการสัมมนาผ่านเว็บทั้งหมด',
        'cta_title': 'พร้อมที่จะก้าวหน้าในอาชีพของคุณแล้วหรือยัง?',
        'cta_subtitle': 'อย่าพลาดโอกาสอันมีค่าเหล่านี้ ลงทะเบียนเรียนหลักสูตรหรือการสัมมนาผ่านเว็บวันนี้!',
        'get_started_btn': 'เริ่มต้นตอนนี้',
        'contact_us_title': 'ติดต่อเรา',
        'contact_us_description': 'มีคำถามเกี่ยวกับหลักสูตรระยะสั้นหรือการสัมมนาผ่านเว็บของเราหรือไม่? ติดต่อเรา!',
        'name_label': 'ชื่อ',
        'email_label': 'อีเมล',
        'message_label': 'ข้อความ',
        'send_message_btn': 'ส่งข้อความ',
        'footer_text': '&copy; 2568 บริการวิชาการของมหาวิทยาลัย สงวนลิขสิทธิ์',
        'privacy_policy': 'นโยบายความเป็นส่วนตัว',
        'terms_of_service': 'ข้อกำหนดในการให้บริการ',
        'duration_label': 'ระยะเวลา',
        'format_label': 'รูปแบบ',
        'certification_label': 'การรับรอง',
        'date_label': 'วันที่',
        'time_label': 'เวลา',
        'speaker_label': 'ผู้บรรยาย',
        'lang_en': 'อังกฤษ',
        'lang_th': 'ไทย',
        'course_detail_title': 'รายละเอียดหลักสูตร',
        'back_to_courses_btn': 'กลับไปที่หลักสูตร',
        'webinar_detail_title': 'รายละเอียดการสัมมนาผ่านเว็บ',
        'back_to_webinars_btn': 'กลับไปที่การสัมมนาผ่านเว็บ',
        'register_page_title': 'ลงทะเบียน',
        'why_register_title': 'ทำไมต้องลงทะเบียน',
        'register_now_btn': 'สมัครสมาชิกเลย',
        'why_register_description': 'การลงทะเบียนช่วยให้คุณได้รับประสบการณ์ที่ดีที่สุดจากระบบของเรา เช่น:',
        'why_register_benefit_1': 'เข้าถึงคอร์สและสัมมนาพิเศษที่สงวนไว้สำหรับสมาชิก',
        'why_register_benefit_2': 'รับใบประกาศนียบัตรและประวัติการเรียนรู้ส่วนตัว',
        'why_register_benefit_3': 'ติดตามข่าวสาร กิจกรรม และสิทธิประโยชน์ล่าสุด',
        'why_register_benefit_4': 'สามารถบันทึกและจัดการข้อมูลส่วนตัวได้อย่างปลอดภัย',
        'why_register_benefit_5': 'รับการสนับสนุนและบริการหลังบ้านที่รวดเร็ว',
        'login_page_title': 'เข้าสู่ระบบ',
        'username_label': 'ชื่อผู้ใช้',
        'password_label': 'รหัสผ่าน',
        'confirm_password_label': 'ยืนยันรหัสผ่าน',
        'register_btn': 'ลงทะเบียน',
        'login_btn': 'เข้าสู่ระบบ',
        'already_have_account': 'มีบัญชีอยู่แล้ว?',
        'no_account_yet': 'ยังไม่มีบัญชี?',
        'logout_btn': 'ออกจากระบบ',
        'welcome_message': 'ยินดีต้อนรับ,',
        'enroll_now_btn': 'ลงทะเบียนเรียนตอนนี้',
        'register_to_enroll': 'ลงทะเบียนหรือเข้าสู่ระบบเพื่อลงทะเบียน',
        'member_type_label': 'ประเภทสมาชิก',
        'mahidol_student': 'นักศึกษามหิดล',
        'grad_student': 'นักศึกษาบัณฑิต',
        'staff': 'บุคลากร',
        'personal': 'บุคคลทั่วไป',
        'other': 'อื่นๆ',
        'gender_label': 'เพศ',
        'age_range_label': 'ช่วงอายุ',
        'country_label': 'ประเทศ',
        'full_name_th_label': 'ชื่อเต็ม (ไทย)',
        'full_name_en_label': 'ชื่อเต็ม (อังกฤษ)',
        'instructors_label': 'ผู้สอน',
        'agenda_label': 'กำหนดการ',
        'location_label': 'สถานที่',
        'registration_fee_label': 'ค่าลงทะเบียน',
        'price_for_you': 'ราคาสำหรับคุณ',
        'i_accept': 'ฉันยอมรับ',
        'accept_policy' : 'นโยบายความเป็นส่วนตัว',
        'accept_terms': 'ข้อกำหนดและเงือนไขการบริการ',
        'receive_news': 'ยินยอมรับข่าวสารประชาสัมพันธ์ทางอีเมล',

        # ป้ายกำกับสำหรับสมาชิก
        'my_registrations_page_title': 'การลงทะเบียนของฉัน',
        'my_payments_page_title': 'การชำระเงินของฉัน',
        'label_event': 'กิจกรรม',
        'label_type': 'ประเภท',
        'label_registered_at': 'ลงทะเบียนเมื่อ',
        'label_payment': 'การชำระเงิน',
        'label_progress': 'ความคืบหน้า',
        'label_amount': 'จำนวนเงิน',
        'label_status': 'สถานะ',
        'label_proof': 'หลักฐานการชำระเงิน',
        'label_started_at': 'เริ่มต้น',
        'label_completed_at': 'เสร็จสิ้น',
        'label_actions': 'การจัดการ',
        'label_member': 'สมาชิก',
        'label_none': 'ไม่มี',
        'label_no_payment_record': 'ไม่มีข้อมูลการชำระเงิน',
        'label_early_bird': 'ราคาพิเศษ',
        'register_for_label': 'ลงทะเบียนสำหรับ:',
        'currency_thb': 'บาท',
        'event_type_course': 'หลักสูตร',
        'event_type_webinar': 'สัมมนาออนไลน์',

        # ข้อความสำหรับสมาชิก
        'message_payments_locked': 'การชำระเงินได้รับการอนุมัติแล้ว ไม่สามารถแก้ไขหลักฐานได้',
        'message_no_payments': 'คุณยังไม่มีรายการชำระเงิน',
        'message_no_registrations': 'คุณยังไม่มีรายการลงทะเบียน',
        'address_type_other_prompt': 'โปรดระบุประเภทที่อยู่',
        'address_country_other_prompt': 'โปรดระบุชื่อประเทศ',
        'address_required_message': 'กรุณากรอกที่อยู่อย่างน้อย 1 รายการ',
        'register_error_generic': 'ไม่สามารถดำเนินการสมัครสมาชิกได้ กรุณาลองใหม่อีกครั้ง',
        'otp_email_missing': 'กรุณาระบุอีเมลเพื่อรับรหัส OTP',

        # ปุ่มสำหรับสมาชิก
        'button_view': 'ดู',
        'button_submit_url': 'ส่ง URL',
        'button_replace_url': 'เปลี่ยน URL',
        'button_upload_file': 'อัปโหลดไฟล์',
        'button_replace_file': 'เปลี่ยนไฟล์',
        'button_view_invoice': 'ดูใบแจ้งหนี้',
        'button_view_receipt': 'ดูใบเสร็จ',
        'button_pay_online': 'ชำระเงินออนไลน์',
        'button_start': 'เริ่มต้น',
        'button_complete': 'เสร็จสิ้น',
        'button_view_certificate': 'ดูใบประกาศ',
        'button_generate_certificate': 'สร้างใบประกาศ',
        'button_download_pdf': 'ดาวน์โหลด PDF',
        'button_back_home': 'กลับหน้าหลัก',
        'button_confirm_registration': 'ยืนยันการลงทะเบียน',
        'button_cancel': 'ยกเลิก',

        # ตัวช่วยอื่นๆ
        'label_fee': 'ค่าธรรมเนียม',
        'label_amount_thb': 'จำนวนเงิน',
        'hero_view_event': 'ดูรายละเอียดกิจกรรม',
        'hero_speakers_label': 'วิทยากร',
        'organization_label': 'หน่วยงาน / สถานที่ทำงาน',
        'organization_placeholder': 'พิมพ์เพื่อค้นหาหรือเพิ่มหน่วยงานใหม่',
        'organization_type_label': 'ประเภทหน่วยงาน',
        'organization_type_other_placeholder': 'โปรดระบุประเภทหน่วยงาน',
        'occupation_label': 'อาชีพ',
        'occupation_other_placeholder': 'โปรดระบุอาชีพ',
        'addresses_section_title': 'ที่อยู่',
        'address_add_button': 'เพิ่มที่อยู่',
        'address_type_current': 'ที่อยู่ปัจจุบัน',
        'address_type_billing': 'ที่อยู่ออกใบกำกับ',
        'address_type_other': 'อื่น ๆ',
        'address_label_field': 'ชื่อที่อยู่ (ถ้ามี)',
        'address_line1_label': 'ที่อยู่บรรทัดที่ 1',
        'address_line2_label': 'ที่อยู่บรรทัดที่ 2',
        'address_city_label': 'อำเภอ / เขต',
        'address_state_label': 'จังหวัด',
        'address_postal_label': 'รหัสไปรษณีย์',
        'address_country_label': 'ประเทศ',
        'address_remove_button': 'ลบที่อยู่นี้',

        # Invoice / Payment i18n
        'invoice_title': 'ใบแจ้งหนี้',
        'invoice_billed_to': 'เรียกเก็บกับ',
        'invoice_details': 'รายละเอียด',
        'invoice_no': 'เลขที่ใบแจ้งหนี้',
        'invoice_amount': 'ยอดเงิน',
        'invoice_status': 'สถานะ',
        'invoice_created': 'วันที่สร้าง',
        'invoice_how_to_pay': 'วิธีชำระเงิน',
        'invoice_bank_info': 'ข้อมูลบัญชีธนาคาร',
        'invoice_total_due': 'ยอดที่ต้องชำระ',
        'invoice_go_to_my_payments': 'ไปที่หน้าการชำระเงินของฉัน',
        'invoice_pay_via_qr': 'ชำระผ่านคิวอาร์',
        'invoice_promptpay_id': 'พร้อมเพย์',
        'invoice_download_pdf': 'ดาวน์โหลด PDF',
        'invoice_pdf_unavailable': 'ไม่สามารถสร้าง PDF ได้',
        'invoice_pay_online': 'ชำระเงินออนไลน์',

        # Email i18n
        'email_registered_for': 'คุณได้ลงทะเบียนสำหรับ',
        'email_amount': 'ยอดเงิน',
        'email_status': 'สถานะ',
        'email_pay_now_or_view_invoice': 'ชำระตอนนี้หรือดูใบแจ้งหนี้:',
        'email_invoice': 'ใบแจ้งหนี้',
        'email_my_payments': 'การชำระเงินของฉัน',
        'email_pay_online': 'ชำระเงินออนไลน์',
        'email_buttons_fallback': 'หากปุ่มไม่ทำงาน ให้คัดลอกลิงก์เหล่านี้ไปวางในเบราว์เซอร์:',

        # Misc
        'not_allowed': 'คุณไม่มีสิทธิ์ดูใบแจ้งหนี้นี้',
        'pdf_unavailable': 'ไม่สามารถสร้างไฟล์ PDF ได้ในขณะนี้',
        'status_pending': 'รอดำเนินการ'
    }
}

# Make translations available as 'texts' for template context
texts = translations    

from . import views
