[pytest]
filterwarnings =
    ignore:Deprecated call to `pkg_resources.declare_namespace\('google'\)`:DeprecationWarning
    ignore:Deprecated call to `pkg_resources.declare_namespace\('google.logging'\)`:DeprecationWarning
