ISSUE_RULES = [
    {
        "key": "diabetes_risk",
        "name": "Diabetes Risk",
        "description": "Fasting glucose is the primary evidence. HbA1c, if available, adds longer-term context. BMI is treated as a risk modifier.",
        "evidence": [
            {
                "key": "fasting_glucose",
                "label": "Fasting glucose",
                "aliases": ["GTT2", "GLU", "FBS", "FBG", "FASTING GLUCOSE", "GLUCOSE"],
                "direction": "upper",
                "thresholds": {"borderline": 100, "abnormal": 126, "critical": 200},
                "role": "core",
                "required": True,
            },
            {
                "key": "hba1c",
                "label": "HbA1c",
                "aliases": ["HBA1C", "HBA1C%", "HBA1C(%)", "HB A1C", "A1C", "HBA1C/GLYCOHEMOGLOBIN"],
                "direction": "upper",
                "thresholds": {"borderline": 5.7, "abnormal": 6.5, "critical": 8.5},
                "role": "core",
                "required": False,
            },
            {
                "key": "bmi",
                "label": "BMI",
                "source": "bmi",
                "direction": "upper",
                "thresholds": {"borderline": 23.0, "abnormal": 25.0, "critical": 30.0},
                "role": "modifier",
                "required": False,
            },
        ],
    },
    {
        "key": "cardiovascular_risk",
        "name": "Cardiovascular Risk",
        "description": "Lipid results are the main evidence. Blood pressure and BMI add risk context if available.",
        "evidence": [
            {
                "key": "ldl",
                "label": "LDL cholesterol",
                "aliases": ["LDL", "LDL2", "LDLD", "LDL-CHOLESTEROL", "LDL CHOLESTEROL"],
                "direction": "upper",
                "thresholds": {"borderline": 100, "abnormal": 130, "critical": 160},
                "role": "core",
                "required": True,
            },
            {
                "key": "hdl",
                "label": "HDL cholesterol",
                "aliases": ["HDLC", "HDL", "HDL-C", "HDL CHOLESTEROL"],
                "direction": "lower",
                "thresholds": {"borderline": 40, "abnormal": 35, "critical": 30},
                "role": "core",
                "required": True,
            },
            {
                "key": "triglycerides",
                "label": "Triglycerides",
                "aliases": ["TG", "TRIGLYCERIDE", "TRIGLYCERIDES"],
                "direction": "upper",
                "thresholds": {"borderline": 150, "abnormal": 200, "critical": 500},
                "role": "core",
                "required": True,
            },
            {
                "key": "total_cholesterol",
                "label": "Total cholesterol",
                "aliases": ["CHO", "CHOL", "CHOLESTEROL", "TOTAL CHOLESTEROL"],
                "direction": "upper",
                "thresholds": {"borderline": 200, "abnormal": 240, "critical": 300},
                "role": "core",
                "required": True,
            },
            {
                "key": "blood_pressure",
                "label": "Blood pressure",
                "source": "blood_pressure",
                "direction": "blood_pressure",
                "thresholds": {
                    "borderline": {"systolic": 130, "diastolic": 80},
                    "abnormal": {"systolic": 140, "diastolic": 90},
                    "critical": {"systolic": 180, "diastolic": 120},
                },
                "role": "core",
                "required": False,
            },
            {
                "key": "bmi",
                "label": "BMI",
                "source": "bmi",
                "direction": "upper",
                "thresholds": {"borderline": 23.0, "abnormal": 25.0, "critical": 30.0},
                "role": "modifier",
                "required": False,
            },
            {
                "key": "triglycerides_hdl_ratio",
                "label": "Triglycerides / HDL ratio",
                "source": "triglycerides_hdl_ratio",
                "direction": "upper",
                "thresholds": {"borderline": 2.5, "abnormal": 4.0, "critical": 6.0},
                "role": "core",
                "required": False,
            },
        ],
    },
    {
        "key": "kidney_health",
        "name": "Kidney Health",
        "description": "Creatinine and eGFR are the main markers. BUN and urine protein add supporting evidence if available.",
        "evidence": [
            {
                "key": "creatinine",
                "label": "Creatinine",
                "aliases": ["CRE", "CREATININE"],
                "direction": "upper",
                "thresholds": {"borderline": 1.3, "abnormal": 1.6, "critical": 2.0},
                "role": "core",
                "required": True,
            },
            {
                "key": "egfr",
                "label": "eGFR",
                "source": "egfr",
                "direction": "lower",
                "thresholds": {"borderline": 90, "abnormal": 60, "critical": 30},
                "role": "core",
                "required": False,
            },
            {
                "key": "bun",
                "label": "BUN",
                "aliases": ["BUN"],
                "direction": "upper",
                "thresholds": {"borderline": 21, "abnormal": 26, "critical": 40},
                "role": "core",
                "required": True,
            },
            {
                "key": "urine_protein",
                "label": "Urine protein",
                "aliases": ["UA05", "URINE PROTEIN", "PROTEIN URINE", "PROTEIN"],
                "direction": "urine_protein",
                "role": "core",
                "required": False,
            },
        ],
    },
    {
        "key": "liver_health",
        "name": "Liver Health",
        "description": "AST, ALT, and ALP/ALK are used as supporting evidence for liver-related concern.",
        "evidence": [
            {
                "key": "ast",
                "label": "AST",
                "aliases": ["AST"],
                "direction": "upper",
                "thresholds": {"borderline": 40, "abnormal": 60, "critical": 100},
                "role": "core",
                "required": True,
            },
            {
                "key": "alt",
                "label": "ALT",
                "aliases": ["ALT"],
                "direction": "upper",
                "thresholds": {"borderline": 40, "abnormal": 60, "critical": 100},
                "role": "core",
                "required": True,
            },
            {
                "key": "alp",
                "label": "ALP",
                "aliases": ["ALK", "ALP", "ALKALINE PHOSPHATASE"],
                "direction": "upper",
                "thresholds": {"borderline": 120, "abnormal": 150, "critical": 300},
                "role": "core",
                "required": False,
            },
        ],
    },
    {
        "key": "obesity_metabolic_health",
        "name": "Obesity / Metabolic Health",
        "description": "BMI leads this section. Triglycerides, HDL, and fasting glucose provide metabolic context.",
        "evidence": [
            {
                "key": "bmi",
                "label": "BMI",
                "source": "bmi",
                "direction": "upper",
                "thresholds": {"borderline": 23.0, "abnormal": 25.0, "critical": 30.0},
                "role": "core",
                "required": True,
            },
            {
                "key": "triglycerides",
                "label": "Triglycerides",
                "aliases": ["TG", "TRIGLYCERIDE", "TRIGLYCERIDES"],
                "direction": "upper",
                "thresholds": {"borderline": 150, "abnormal": 200, "critical": 500},
                "role": "core",
                "required": True,
            },
            {
                "key": "hdl",
                "label": "HDL cholesterol",
                "aliases": ["HDLC", "HDL", "HDL-C", "HDL CHOLESTEROL"],
                "direction": "lower",
                "thresholds": {"borderline": 40, "abnormal": 35, "critical": 30},
                "role": "core",
                "required": True,
            },
            {
                "key": "fasting_glucose",
                "label": "Fasting glucose",
                "aliases": ["GTT2", "GLU", "FBS", "FBG", "FASTING GLUCOSE", "GLUCOSE"],
                "direction": "upper",
                "thresholds": {"borderline": 100, "abnormal": 126, "critical": 200},
                "role": "core",
                "required": True,
            },
            {
                "key": "triglycerides_hdl_ratio",
                "label": "Triglycerides / HDL ratio",
                "source": "triglycerides_hdl_ratio",
                "direction": "upper",
                "thresholds": {"borderline": 2.5, "abnormal": 4.0, "critical": 6.0},
                "role": "core",
                "required": False,
            },
        ],
    },
    {
        "key": "anemia_concern",
        "name": "Anemia Concern",
        "description": "Hemoglobin and hematocrit are the main evidence. MCV is added when available.",
        "evidence": [
            {
                "key": "hemoglobin",
                "label": "Hemoglobin",
                "aliases": ["CBC11", "HB", "HGB", "HEMOGLOBIN"],
                "direction": "lower",
                "thresholds_by_gender": {
                    "male": {"borderline": 13.5, "abnormal": 12.0, "critical": 10.0},
                    "female": {"borderline": 12.0, "abnormal": 10.5, "critical": 8.0},
                    "default": {"borderline": 13.0, "abnormal": 11.0, "critical": 8.0},
                },
                "role": "core",
                "required": True,
            },
            {
                "key": "hematocrit",
                "label": "Hematocrit",
                "aliases": ["HCT", "HEMATOCRIT", "CBC12"],
                "direction": "lower",
                "thresholds_by_gender": {
                    "male": {"borderline": 40, "abnormal": 36, "critical": 30},
                    "female": {"borderline": 36, "abnormal": 32, "critical": 26},
                    "default": {"borderline": 38, "abnormal": 34, "critical": 28},
                },
                "role": "core",
                "required": True,
            },
            {
                "key": "mcv",
                "label": "MCV",
                "aliases": ["MCV", "CBC13"],
                "direction": "range",
                "thresholds": {
                    "low_borderline": 80,
                    "low_abnormal": 75,
                    "low_critical": 70,
                    "high_borderline": 99,
                    "high_abnormal": 105,
                    "high_critical": 110,
                },
                "role": "core",
                "required": False,
            },
        ],
    },
    {
        "key": "gout_risk",
        "name": "Gout Risk",
        "description": "Uric acid is the main evidence. Creatinine adds context if available.",
        "evidence": [
            {
                "key": "uric_acid",
                "label": "Uric acid",
                "aliases": ["UA", "URIC ACID", "URIC", "URIC ACID SERUM"],
                "direction": "upper",
                "thresholds_by_gender": {
                    "male": {"borderline": 7.0, "abnormal": 8.0, "critical": 10.0},
                    "female": {"borderline": 6.0, "abnormal": 7.0, "critical": 9.0},
                    "default": {"borderline": 7.0, "abnormal": 8.0, "critical": 10.0},
                },
                "role": "core",
                "required": True,
            },
            {
                "key": "creatinine",
                "label": "Creatinine",
                "aliases": ["CRE", "CREATININE"],
                "direction": "upper",
                "thresholds": {"borderline": 1.3, "abnormal": 1.6, "critical": 2.0},
                "role": "modifier",
                "required": False,
            },
        ],
    },
]
