HEALTH_RISK_COPY = {
    "th": {
        "page_title": "รายงานความเสี่ยงสุขภาพ",
        "page_subtitle": "รายงานสุขภาพแบบจัดกลุ่มตามความเสี่ยง",
        "top_concerns": "3 ความเสี่ยงสำคัญ",
        "issue_cards": "ความเสี่ยงสุขภาพ",
        "ai_summary_title": "สรุปสิ่งที่สำคัญจากผลการตรวจด้วย AI",
        "ai_summary_subtitle": "ภาพรวมของความเสี่ยงและสิ่งที่ควรจับตาจากผลตรวจชุดนี้",
        "ai_top_concerns_label": "ความเสี่ยงหลัก",
        "ai_what_matters_label": "สิ่งที่ควรสนใจ",
        "loading_top_concerns": "กำลังโหลดความเสี่ยงหลัก",
        "loading_ai_summary": "กำลังโหลดสรุปจาก Typhoon AI",
        "loading_issue_cards": "กำลังโหลดความเสี่ยงสุขภาพ",
        "related_videos_title": "วิดีโอแนะนำที่เกี่ยวข้อง",
        "explore_related_videos": "ดูวิดีโอที่เกี่ยวข้อง",
        "no_related_videos": "ยังไม่มีวิดีโอที่เกี่ยวข้องในตอนนี้",
        "no_related_videos_help": "ระบบจะแสดงวิดีโอแนะนำไว้ในส่วนนี้เมื่อมีข้อมูลที่ตรงกับความเสี่ยงของคุณ",
        "videos_page_title": "วิดีโอให้ความรู้ด้านสุขภาพ",
        "videos_page_subtitle": "รวมวิดีโอทั้งหมดพร้อมรายละเอียดประกอบการค้นหาและการอ้างอิง",
        "videos_page_all_title": "วิดีโอทั้งหมด",
        "videos_page_metadata": "รายละเอียดวิดีโอ",
        "videos_page_back": "กลับไปยังรายงาน",
        "toggle_all_results": "ดูผลทั้งหมด",
        "other_results": "ผลตรวจครั้งอื่น ๆ",
        "show_evidence": "แสดงตัวบ่งชี้",
        "hide_evidence": "ซ่อนตัวบ่งชี้",
        "legacy_page_title": "รายงานผลการตรวจสุขภาพ",
        "legacy_page_subtitle": "ระบบรายงานผลสุขภาพแบบอัจฉริยะ",
        "physical_exam_title": "การตรวจร่างกายทั่วไป (PHYSICAL EXAMINATION)",
        "blood_chemistry_title": "การตรวจทางเคมี (Blood Chemistry)",
        "risk_snapshot_title": "3 ความเสี่ยงสำคัญและตัวบ่งชี้สนับสนุน",
        "risk_snapshot_subtitle": "สรุปย่อจากผลตรวจที่เกี่ยวข้องกับความเสี่ยงสุขภาพ",
        "legacy_switch_to_th": "ภาษาไทย",
        "legacy_switch_to_en": "English",
        "issue_name": {
            "diabetes_risk": "ความเสี่ยงเบาหวาน",
            "cardiovascular_risk": "ความเสี่ยงโรคหัวใจและหลอดเลือด",
            "kidney_health": "สุขภาพไต",
            "liver_health": "สุขภาพตับ",
            "obesity_metabolic_health": "ภาวะอ้วน / เมตาบอลิก",
            "anemia_concern": "ภาวะซีด",
            "gout_risk": "ความเสี่ยงโรคเกาต์",
        },
        "description": {
            "diabetes_risk": "ระดับน้ำตาลขณะอดอาหารเป็นตัวบ่งชี้สำคัญ HbA1c หากมีจะช่วยดูแนวโน้มระยะยาว และ BMI ใช้เป็นตัวปรับความเสี่ยง",
            "cardiovascular_risk": "ไขมันในเลือดเป็นหลัก ความดันโลหิต BMI และอัตราส่วนไตรกลีเซอไรด์ต่อ HDL ช่วยเพิ่มบริบทของความเสี่ยง",
            "kidney_health": "Creatinine และ eGFR เป็นตัวชี้วัดหลัก BUN และโปรตีนในปัสสาวะใช้เป็นตัวบ่งชี้สนับสนุน",
            "liver_health": "AST, ALT และ ALP/ALK ใช้เป็นตัวบ่งชี้สนับสนุนความผิดปกติของตับ",
            "obesity_metabolic_health": "BMI เป็นตัวนำ Triglycerides, HDL, อัตราส่วนไตรกลีเซอไรด์ต่อ HDL และระดับน้ำตาลช่วยสะท้อนเมตาบอลิกโดยรวม",
            "anemia_concern": "Hemoglobin และ Hematocrit เป็นตัวบ่งชี้สำคัญ MCV ช่วยเติมรายละเอียดหากมีข้อมูล",
            "gout_risk": "กรดยูริกเป็นตัวบ่งชี้หลัก Creatinine ช่วยเพิ่มบริบทความเสี่ยง",
        },
        "evidence_completeness": "ความครบถ้วนของตัวบ่งชี้",
        "missing_evidence": "ตัวบ่งชี้ที่ยังไม่มี",
        "complete": "ตัวบ่งชี้ครบตามรายการที่กำหนด",
        "score": "คะแนน",
        "concern_score": "คะแนนความเสี่ยง",
        "no_concern": "ยังไม่พบความเสี่ยงจากผลตรวจที่มีอยู่",
        "mild": "เริ่มเสี่ยง",
        "moderate": "เสี่ยงปานกลาง",
        "high": "เสี่ยงสูง",
        "evidence_incomplete": "ตัวบ่งชี้ยังไม่ครบ",
        "not_diagnosis": "รายงานนี้ไม่ใช่การวินิจฉัย",
        "supporting_findings": "ตัวบ่งชี้สนับสนุน",
        "status": {
            "normal": "ปกติ",
            "borderline": "เริ่มมีความเสี่ยง",
            "abnormal": "ผิดปกติ",
            "critical": "ผิดปกติรุนแรง",
            "missing": "ไม่มีข้อมูล",
        },
        "table": {
            "test_name": "รายการตรวจ",
            "value": "ค่า",
            "unit": "หน่วย",
            "reference": "เกณฑ์อ้างอิง",
            "status": "สถานะ",
            "score": "คะแนน",
        },
        "back_to_legacy": "กลับไปดูรายงานผลตรวจแบบเดิม",
        "switch_to_th": "ภาษาไทย",
        "switch_to_en": "English",
        "switch_hint": "สลับภาษา",
        "disclaimer_label": "สำคัญ",
        "lab_no": "LAB NO",
        "issue_name": {
            "diabetes_risk": "ความเสี่ยงเบาหวาน",
            "cardiovascular_risk": "ความเสี่ยงโรคหัวใจและหลอดเลือด",
            "kidney_health": "สุขภาพไต",
            "liver_health": "สุขภาพตับ",
            "obesity_metabolic_health": "ภาวะอ้วน / เมตาบอลิก",
            "anemia_concern": "ภาวะซีด",
            "gout_risk": "ความเสี่ยงโรคเกาต์",
        },
        "description": {
            "diabetes_risk": "ระดับน้ำตาลขณะอดอาหารเป็นตัวบ่งชี้สำคัญ HbA1c หากมีจะช่วยดูแนวโน้มระยะยาว และ BMI ใช้เป็นตัวปรับความเสี่ยง",
            "cardiovascular_risk": "ไขมันในเลือดเป็นหลัก ความดันโลหิตและ BMI ช่วยเพิ่มบริบทของความเสี่ยง",
            "kidney_health": "Creatinine และ eGFR เป็นตัวชี้วัดหลัก BUN และโปรตีนในปัสสาวะใช้เป็นตัวบ่งชี้สนับสนุน",
            "liver_health": "AST, ALT และ ALP/ALK ใช้เป็นตัวบ่งชี้สนับสนุนความผิดปกติของตับ",
            "obesity_metabolic_health": "BMI เป็นตัวนำ Triglycerides, HDL และระดับน้ำตาลช่วยสะท้อนเมตาบอลิกโดยรวม",
            "anemia_concern": "Hemoglobin และ Hematocrit เป็นตัวบ่งชี้สำคัญ MCV ช่วยเติมรายละเอียดหากมีข้อมูล",
            "gout_risk": "กรดยูริกเป็นตัวบ่งชี้หลัก Creatinine ช่วยเพิ่มบริบทความเสี่ยง",
        },
        "evidence_label": {
            "fasting_glucose": "ระดับน้ำตาลขณะอดอาหาร",
            "hba1c": "HbA1c",
            "bmi": "BMI",
            "ldl": "LDL cholesterol",
            "hdl": "HDL cholesterol",
            "triglycerides": "Triglycerides",
            "triglycerides_hdl_ratio": "Triglycerides / HDL ratio",
            "total_cholesterol": "Total cholesterol",
            "blood_pressure": "ความดันโลหิต",
            "creatinine": "Creatinine",
            "egfr": "eGFR",
            "bun": "BUN",
            "urine_protein": "โปรตีนในปัสสาวะ",
            "ast": "AST",
            "alt": "ALT",
            "alp": "ALP",
            "hemoglobin": "Hemoglobin",
            "hematocrit": "Hematocrit",
            "mcv": "MCV",
            "uric_acid": "กรดยูริก",
        },
    },
    "en": {
        "page_title": "Health Risk Report",
        "page_subtitle": "Health report organized by concern level",
        "top_concerns": "Top 3 health concerns",
        "issue_cards": "Health Concerns",
        "ai_summary_title": "AI summary of key findings",
        "ai_summary_subtitle": "Overall risk picture and what matters from this result set",
        "ai_top_concerns_label": "Top concerns",
        "ai_what_matters_label": "What matters",
        "loading_top_concerns": "Loading top concerns",
        "loading_ai_summary": "Loading Typhoon AI summary",
        "loading_issue_cards": "Loading health concerns",
        "related_videos_title": "Recommended related videos",
        "explore_related_videos": "Explore related videos",
        "no_related_videos": "No related videos are available yet",
        "no_related_videos_help": "Recommended videos will appear here when the report finds a matching concern.",
        "videos_page_title": "Health Education Videos",
        "videos_page_subtitle": "Browse the full catalog with metadata for each video.",
        "videos_page_all_title": "All videos",
        "videos_page_metadata": "Video metadata",
        "videos_page_back": "Back to report",
        "toggle_all_results": "View all results",
        "other_results": "Other Results",
        "show_evidence": "Show markers",
        "hide_evidence": "Hide markers",
        "legacy_page_title": "Health Check-up Report",
        "legacy_page_subtitle": "Smart Health Check Up Report",
        "physical_exam_title": "Physical Examination",
        "blood_chemistry_title": "Blood Chemistry",
        "risk_snapshot_title": "Top concerns and supporting markers",
        "risk_snapshot_subtitle": "A concise summary of the results related to health concerns",
        "legacy_switch_to_th": "ภาษาไทย",
        "legacy_switch_to_en": "English",
        "issue_name": {
            "diabetes_risk": "Diabetes Risk",
            "cardiovascular_risk": "Cardiovascular Risk",
            "kidney_health": "Kidney Health",
            "liver_health": "Liver Health",
            "obesity_metabolic_health": "Obesity / Metabolic Health",
            "anemia_concern": "Anemia Concern",
            "gout_risk": "Gout Risk",
        },
        "description": {
            "diabetes_risk": "Fasting glucose is the primary evidence. HbA1c, if available, adds longer-term context. BMI is treated as a risk modifier.",
            "cardiovascular_risk": "Lipid results are the main evidence. Blood pressure, BMI, and the triglycerides-to-HDL ratio add risk context if available.",
            "kidney_health": "Creatinine and eGFR are the main markers. BUN and urine protein add supporting evidence if available.",
            "liver_health": "AST, ALT, and ALP/ALK are used as supporting evidence for liver-related concern.",
            "obesity_metabolic_health": "BMI leads this section. Triglycerides, HDL, the triglycerides-to-HDL ratio, and fasting glucose provide metabolic context.",
            "anemia_concern": "Hemoglobin and hematocrit are the main evidence. MCV is added when available.",
            "gout_risk": "Uric acid is the main evidence. Creatinine adds context if available.",
        },
        "evidence_completeness": "Evidence completeness",
        "missing_evidence": "Missing evidence",
        "complete": "Complete for configured evidence",
        "score": "Score",
        "concern_score": "Concern score",
        "no_concern": "No current concern based on available results",
        "mild": "Mild concern",
        "moderate": "Moderate concern",
        "high": "High concern",
        "evidence_incomplete": "Evidence is incomplete",
        "not_diagnosis": "This is not a diagnosis",
        "supporting_findings": "Supporting findings",
        "status": {
            "normal": "Normal",
            "borderline": "Borderline",
            "abnormal": "Abnormal",
            "critical": "Critical",
            "missing": "Missing evidence",
        },
        "table": {
            "test_name": "Test name",
            "value": "Value",
            "unit": "Unit",
            "reference": "Reference",
            "status": "Status",
            "score": "Score",
        },
        "back_to_legacy": "Back to the legacy lab report",
        "switch_to_th": "ภาษาไทย",
        "switch_to_en": "English",
        "switch_hint": "Switch language",
        "disclaimer_label": "Important",
        "lab_no": "LAB NO",
        "issue_name": {
            "diabetes_risk": "Diabetes Risk",
            "cardiovascular_risk": "Cardiovascular Risk",
            "kidney_health": "Kidney Health",
            "liver_health": "Liver Health",
            "obesity_metabolic_health": "Obesity / Metabolic Health",
            "anemia_concern": "Anemia Concern",
            "gout_risk": "Gout Risk",
        },
        "description": {
            "diabetes_risk": "Fasting glucose is the primary evidence. HbA1c, if available, adds longer-term context. BMI is treated as a risk modifier.",
            "cardiovascular_risk": "Lipid results are the main evidence. Blood pressure and BMI add risk context if available.",
            "kidney_health": "Creatinine and eGFR are the main markers. BUN and urine protein add supporting evidence if available.",
            "liver_health": "AST, ALT, and ALP/ALK are used as supporting evidence for liver-related concern.",
            "obesity_metabolic_health": "BMI leads this section. Triglycerides, HDL, and fasting glucose provide metabolic context.",
            "anemia_concern": "Hemoglobin and hematocrit are the main evidence. MCV is added when available.",
            "gout_risk": "Uric acid is the main evidence. Creatinine adds context if available.",
        },
        "evidence_label": {
            "fasting_glucose": "Fasting glucose",
            "hba1c": "HbA1c",
            "bmi": "BMI",
            "ldl": "LDL cholesterol",
            "hdl": "HDL cholesterol",
            "triglycerides": "Triglycerides",
            "triglycerides_hdl_ratio": "Triglycerides / HDL ratio",
            "total_cholesterol": "Total cholesterol",
            "blood_pressure": "Blood pressure",
            "creatinine": "Creatinine",
            "egfr": "eGFR",
            "bun": "BUN",
            "urine_protein": "Urine protein",
            "ast": "AST",
            "alt": "ALT",
            "alp": "ALP",
            "hemoglobin": "Hemoglobin",
            "hematocrit": "Hematocrit",
            "mcv": "MCV",
            "uric_acid": "Uric acid",
        },
    },
}


def get_health_risk_copy(lang):
    return HEALTH_RISK_COPY["th" if str(lang).lower().startswith("th") else "en"]
