"""Edited nullable become False in question_type column for ComplaintRecord Models

Revision ID: 01ccd42fda23
Revises: a4fa35e6428d
Create Date: 2024-04-02 15:42:24.949631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ccd42fda23'
down_revision = 'a4fa35e6428d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.alter_column('question_type',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.alter_column('question_type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
