"""added association table for PDPA requests and datasets

Revision ID: 02cc87f01969
Revises: ee616137f395
Create Date: 2022-05-22 22:36:41.052058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cc87f01969'
down_revision = 'ee616137f395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdpa_request_datasets',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('pdpa_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['db_datasets.id'], ),
    sa.ForeignKeyConstraint(['pdpa_request_id'], ['pdpa_requests.id'], ),
    sa.PrimaryKeyConstraint('dataset_id', 'pdpa_request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdpa_request_datasets')
    # ### end Alembic commands ###
