"""added desc column in PARound table

Revision ID: 03114e93273a
Revises: f0d431a7e1b2
Create Date: 2023-11-20 09:23:35.736909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03114e93273a'
down_revision = 'f0d431a7e1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_rounds', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
