"""added expired_reason column in Process table

Revision ID: 03365bd3c37f
Revises: 9a7c2e1f4b6d
Create Date: 2026-08-21 14:04:42.503684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03365bd3c37f'
down_revision = '9a7c2e1f4b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_survey_results')
    with op.batch_alter_table('db_processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_processes', schema=None) as batch_op:
        batch_op.drop_column('expired_reason')
    # ### end Alembic commands ###
