"""added reporter id and the relationship to the model

Revision ID: 03754b1580b4
Revises: 564b37502cc1
Create Date: 2018-09-10 05:23:10.840258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03754b1580b4'
down_revision = '564b37502cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lis_results', 'reported_by', type_=sa.String())
    op.create_foreign_key(None, 'lis_results', 'students', ['reported_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lis_results', type_='foreignkey')
    op.alter_column('lis_results', 'reported_by', type_=sa.Integer())
    # ### end Alembic commands ###
