"""Added AlumniInformation model

Revision ID: 037df1943da6
Revises: e6db8582c619
Create Date: 2023-03-15 13:27:14.361000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037df1943da6'
down_revision = 'e6db8582c619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('th_title', sa.String(), nullable=True),
    sa.Column('th_firstname', sa.String(), nullable=True),
    sa.Column('th_lastname', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('workplace', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumni_information')
    # ### end Alembic commands ###
