"""created invited_document_id column in StaffSeminarAttend table

Revision ID: 03b656caee36
Revises: 774d718bf1cc
Create Date: 2022-08-04 10:22:44.364361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b656caee36'
down_revision = '774d718bf1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_seminar_attends', sa.Column('document_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_seminar_attends', 'document_id')
    # ### end Alembic commands ###
