"""Added cashier, detail, and list electronic receipt model

Revision ID: 03ca7f8d689c
Revises: aeb275954132
Create Date: 2022-08-06 16:12:30.143000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ca7f8d689c'
down_revision = 'aeb275954132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electronic_receipt_cashier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electronic_receipt_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('copy_number', sa.Integer(), nullable=True),
    sa.Column('book_number', sa.String(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('cancel_comment', sa.Text(), nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.String(), nullable=True),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('paid_amount', sa.Numeric(), nullable=True),
    sa.Column('card_number', sa.String(length=16), nullable=True),
    sa.Column('issued_for', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cashier_id'], ['electronic_receipt_cashier.id'], ),
    sa.ForeignKeyConstraint(['issuer_id'], ['electronic_receipt_cashier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electronic_receipt_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['electronic_receipt_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electronic_receipt_lists')
    op.drop_table('electronic_receipt_details')
    op.drop_table('electronic_receipt_cashier')
    # ### end Alembic commands ###
