"""added chem items table

Revision ID: 04ba270ed7d9
Revises: 06d38f2d806f
Create Date: 2019-01-29 15:20:13.600469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ba270ed7d9'
down_revision = '06d38f2d806f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chemdb_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('msds', sa.String(length=255), nullable=True),
    sa.Column('cas', sa.String(length=255), nullable=True),
    sa.Column('company_code', sa.String(length=255), nullable=True),
    sa.Column('container_size', sa.Numeric(), nullable=True),
    sa.Column('container_unit', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['staff_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemdb_items')
    # ### end Alembic commands ###
