"""Added appointment_date column in ServiceSample model

Revision ID: 04deb3881cc8
Revises: e740f09467cf
Create Date: 2025-08-22 13:36:45.171936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04deb3881cc8'
down_revision = 'e740f09467cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_samples', schema=None) as batch_op:
        batch_op.drop_column('appointment_date')
    # ### end Alembic commands ###
