"""added parent_kpi_id field for cascading KPI

Revision ID: 0616427692dc
Revises: bb72d5f65f90
Create Date: 2024-01-16 10:59:14.406377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0616427692dc'
down_revision = 'bb72d5f65f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_kpi_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'kpis', ['parent_kpi_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_kpi_id')

    # ### end Alembic commands ###
