"""deleted column sap_no in table StaffPersonalInfo

Revision ID: 07261be9d90b
Revises: 100892ba72ee
Create Date: 2021-10-28 14:15:57.510776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07261be9d90b'
down_revision = '100892ba72ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_personal_info', 'sap_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_personal_info', sa.Column('sap_no', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
