"""Added qrcode, start guarantee date and end guarantee date column in procurement detail model

Revision ID: 08a03f1ab52e
Revises: 4bd565e9619c
Create Date: 2022-06-21 15:07:13.208000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a03f1ab52e'
down_revision = '4bd565e9619c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_details', sa.Column('end_guarantee_date', sa.Date(), nullable=True))
    op.add_column('procurement_details', sa.Column('qrcode', sa.Text(), nullable=True))
    op.add_column('procurement_details', sa.Column('start_guarantee_date', sa.Date(), nullable=True))
    op.drop_column('procurement_details', 'desc')
    op.drop_column('procurement_details', 'university_no')
    op.drop_column('procurement_details', 'registration_no')
    op.drop_column('procurement_details', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_details', sa.Column('quantity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('procurement_details', sa.Column('registration_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('procurement_details', sa.Column('university_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('procurement_details', sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('procurement_details', 'start_guarantee_date')
    op.drop_column('procurement_details', 'qrcode')
    op.drop_column('procurement_details', 'end_guarantee_date')
    # ### end Alembic commands ###
