"""deleted criterion_id PAFunctionalCompetencyEvaluation table

Revision ID: 08dfd10678fa
Revises: 022f675c964a
Create Date: 2023-11-10 15:56:02.262662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08dfd10678fa'
down_revision = '022f675c964a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_functional_competency_evaluations', schema=None) as batch_op:
        batch_op.drop_constraint('pa_functional_competency_evaluations_criterion_id_fkey', type_='foreignkey')
        batch_op.drop_column('criterion_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_functional_competency_evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criterion_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pa_functional_competency_evaluations_criterion_id_fkey', 'pa_functional_competency_indicators', ['criterion_id'], ['id'])

    # ### end Alembic commands ###
