"""added a creator field for manually inserted record

Revision ID: 0a631453b876
Revises: e150d7c88d37
Create Date: 2026-07-22 16:38:27.550234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a631453b876'
down_revision = 'e150d7c88d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ce_satisfaction_survey_access_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('ce_satisfaction_survey_access_tokens_token_hash_key', type_='unique')

    with op.batch_alter_table('ce_satisfaction_survey_responses', schema=None) as batch_op:
        batch_op.drop_constraint('ce_satisfaction_survey_responses_registration_id_key', type_='unique')
        batch_op.drop_index('ix_ce_satisfaction_survey_responses_registration_id')
        batch_op.create_index(batch_op.f('ix_ce_satisfaction_survey_responses_registration_id'), ['registration_id'], unique=True)

    with op.batch_alter_table('staff_work_logins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff_account', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_work_logins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')

    with op.batch_alter_table('ce_satisfaction_survey_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ce_satisfaction_survey_responses_registration_id'))
        batch_op.create_index('ix_ce_satisfaction_survey_responses_registration_id', ['registration_id'], unique=False)
        batch_op.create_unique_constraint('ce_satisfaction_survey_responses_registration_id_key', ['registration_id'])

    with op.batch_alter_table('ce_satisfaction_survey_access_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint('ce_satisfaction_survey_access_tokens_token_hash_key', ['token_hash'])

    # ### end Alembic commands ###
