"""Added thai_language, eng_language, thai_copy_language and eng_copy_language columns in ServiceRequest model

Revision ID: 0bf4ae18dcac
Revises: 91e4ca4c3f90
Create Date: 2025-06-12 13:41:19.914299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bf4ae18dcac'
down_revision = '91e4ca4c3f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thai_language', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('eng_language', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('thai_copy_language', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('eng_copy_language', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('eng_copy_language')
        batch_op.drop_column('thai_copy_language')
        batch_op.drop_column('eng_language')
        batch_op.drop_column('thai_language')
    # ### end Alembic commands ###
