"""Renamed approved_at column in ServiceFinalResultItemReversion model

Revision ID: 0c4c3b77eaa4
Revises: b4ef604cb0da
Create Date: 2026-07-20 13:10:45.305115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c4c3b77eaa4'
down_revision = 'b4ef604cb0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_final_result_item_reversions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column(' approved_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_final_result_item_reversions', schema=None) as batch_op:
        batch_op.add_column(sa.Column(' approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('approved_at')
    # ### end Alembic commands ###
