"""added title and abstract fields

Revision ID: 0c892eac47fa
Revises: bbe85efe3c46
Create Date: 2020-11-01 21:10:22.366762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c892eac47fa'
down_revision = 'bbe85efe3c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_pub', sa.Column('abstract', sa.Text(), nullable=True))
    op.add_column('research_pub', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_pub', 'title')
    op.drop_column('research_pub', 'abstract')
    # ### end Alembic commands ###
