"""Deleted lab_id and lab column in ServiceAdmin model

Revision ID: 0db3cceb04fa
Revises: 6430d4c21b6a
Create Date: 2025-05-13 11:10:02.784592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0db3cceb04fa'
down_revision = '6430d4c21b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_admins', schema=None) as batch_op:
        batch_op.drop_constraint('service_admins_lab_id_fkey', type_='foreignkey')
        batch_op.drop_column('lab_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('service_admins_lab_id_fkey', 'service_labs', ['lab_id'], ['id'])
    # ### end Alembic commands ###
