"""Edited MeetingPoll Model and Added MeetingPollTeam

Revision ID: 0e84f630c3e4
Revises: 4a92f1c5b43f
Create Date: 2023-11-01 13:17:27.044502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e84f630c3e4'
down_revision = '4a92f1c5b43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_poll_teams',
    sa.Column('group_detail_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_detail_id'], ['staff_group_details.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['meeting_polls.id'], ),
    sa.PrimaryKeyConstraint('group_detail_id', 'poll_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_poll_teams')
    # ### end Alembic commands ###
