"""added instructor model and the association table with the course model

Revision ID: 0f54b9a5a9cd
Revises: 7c07728f2f62
Create Date: 2021-04-19 05:59:55.105183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f54b9a5a9cd'
down_revision = '7c07728f2f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eduqa_course_instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['staff_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eduqa_course_instructor_assoc',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['eduqa_courses.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['eduqa_course_instructors.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eduqa_course_instructor_assoc')
    op.drop_table('eduqa_course_instructors')
    # ### end Alembic commands ###
