"""Added taxpayer_identification_no, address and name columns in ServiceQuotation model

Revision ID: 0fdeb929b95f
Revises: 5556a6971f6e
Create Date: 2025-06-12 16:03:17.692071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fdeb929b95f'
down_revision = '5556a6971f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('taxpayer_identification_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotations', schema=None) as batch_op:
        batch_op.drop_column('taxpayer_identification_no')
        batch_op.drop_column('address')
        batch_op.drop_column('name')
    # ### end Alembic commands ###
