"""Added customer_id, customer, admin_id, admin, created_at and data column in ServiceRequest model

Revision ID: 11c2cb86451c
Revises: ee53e75470ab
Create Date: 2024-09-06 11:13:40.169397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11c2cb86451c'
down_revision = 'ee53e75470ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_foreign_key(None, 'staff_account', ['admin_id'], ['id'])
        batch_op.create_foreign_key(None, 'service_customer_infos', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data')
        batch_op.drop_column('created_at')
        batch_op.drop_column('admin_id')
        batch_op.drop_column('customer_id')
    # ### end Alembic commands ###
