"""added MeetingPollParticipant model

Revision ID: 11db55c9b648
Revises: 7b15adf36c0a
Create Date: 2023-09-13 17:04:15.592586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11db55c9b648'
down_revision = '7b15adf36c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_poll_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['staff_account.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['meeting_polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_poll_participants')
    # ### end Alembic commands ###
