"""Deleted nullable in title, fistname and lastname column in ServiceCustomerInfo model

Revision ID: 11df50c72f2b
Revises: 0eeb18026af0
Create Date: 2024-05-01 13:27:44.124191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11df50c72f2b'
down_revision = '0eeb18026af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_infos', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_infos', schema=None) as batch_op:
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
