"""added agricultural types model

Revision ID: 1450978b43fa
Revises: d3faa3475522
Create Date: 2018-01-24 22:41:41.238974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1450978b43fa'
down_revision = 'd3faa3475522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_agritype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'food_farms', sa.Column('agritype', sa.Integer(), nullable=True))
    op.add_column(u'food_farms', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column(u'food_farms', sa.Column('province_id', sa.Integer(), nullable=True))
    op.add_column(u'food_farms', sa.Column('subdistrict_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'food_farms', 'subdistricts', ['subdistrict_id'], ['id'])
    op.create_foreign_key(None, 'food_farms', 'provinces', ['province_id'], ['id'])
    op.create_foreign_key(None, 'food_farms', 'food_agritype', ['agritype'], ['id'])
    op.create_foreign_key(None, 'food_farms', 'districts', ['district_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food_farms', type_='foreignkey')
    op.drop_constraint(None, 'food_farms', type_='foreignkey')
    op.drop_constraint(None, 'food_farms', type_='foreignkey')
    op.drop_constraint(None, 'food_farms', type_='foreignkey')
    op.drop_column(u'food_farms', 'subdistrict_id')
    op.drop_column(u'food_farms', 'province_id')
    op.drop_column(u'food_farms', 'district_id')
    op.drop_column(u'food_farms', 'agritype')
    op.drop_table('food_agritype')
    # ### end Alembic commands ###
