"""add column Employee ID

Revision ID: 15943f1b4409
Revises: efc8cd27b0f5
Create Date: 2022-06-16 20:41:02.479000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15943f1b4409'
down_revision = 'efc8cd27b0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comhealth_customers', sa.Column('emp_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comhealth_customers', 'emp_id')
    # ### end Alembic commands ###
