"""Added required_information column in SoftwareRequestDetail model

Revision ID: 15ec4c2dd8a0
Revises: d56e78a40b40
Create Date: 2025-04-09 10:04:03.009223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15ec4c2dd8a0'
down_revision = 'd56e78a40b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
