"""Updated order by start_date and added other_activity in PurchaseTrackerStatus Model

Revision ID: 15f8b277820d
Revises: cb10ca002e11
Create Date: 2022-03-18 16:53:56.262000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f8b277820d'
down_revision = 'cb10ca002e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_statuses', sa.Column('other_activity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker_statuses', 'other_activity')
    # ### end Alembic commands ###
