"""Deleted detail column in SoftwareRequestTestResult model

Revision ID: 164585e66baf
Revises: af8ead9a95e1
Create Date: 2026-04-27 14:34:36.666605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164585e66baf'
down_revision = 'af8ead9a95e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_test_results', schema=None) as batch_op:
        batch_op.drop_column('detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_test_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
