"""Added customer_id, customer, customer_account_id and customer_account column in ServiceCustomerAddress model

Revision ID: 17111e553688
Revises: 4a903981cc42
Create Date: 2024-12-04 11:24:11.962855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17111e553688'
down_revision = '4a903981cc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'service_customer_accounts', ['customer_account_id'], ['id'])
        batch_op.create_foreign_key(None, 'service_customer_infos', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customer_account_id')
        batch_op.drop_column('customer_id')
    # ### end Alembic commands ###
