"""Deleted customer_id, customer, customer_account_id and customer_account column in ServiceRequest model

Revision ID: 18c3c53c4bc4
Revises: 7f0d6c4bbd7f
Create Date: 2025-01-28 10:47:04.622764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18c3c53c4bc4'
down_revision = '7f0d6c4bbd7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_constraint('service_requests_customer_account_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('service_requests_customer_id_fkey', type_='foreignkey')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('customer_account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('service_requests_customer_id_fkey', 'service_customer_infos', ['customer_id'], ['id'])
        batch_op.create_foreign_key('service_requests_customer_account_id_fkey', 'service_customer_accounts', ['customer_account_id'], ['id'])
    # ### end Alembic commands ###
