"""Added modified_at column in ServiceResult model

Revision ID: 1c80ed5edd19
Revises: 237da88ba1a9
Create Date: 2025-01-03 13:23:26.903698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c80ed5edd19'
down_revision = '237da88ba1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_results', schema=None) as batch_op:
        batch_op.drop_column('modified_at')
    # ### end Alembic commands ###
