"""Deleted lab_id and lab column in ServiceLab model

Revision ID: 1d9adfc41fb1
Revises: 3ed07b06a8b7
Create Date: 2024-11-07 13:53:41.400084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d9adfc41fb1'
down_revision = '3ed07b06a8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_admins', schema=None) as batch_op:
        batch_op.drop_constraint('service_admins_lab_id_fkey', type_='foreignkey')
        batch_op.drop_column('lab_id')

    with op.batch_alter_table('service_labs', schema=None) as batch_op:
        batch_op.drop_column('lab_name')
        batch_op.drop_column('lab')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lab_name', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('service_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('service_admins_lab_id_fkey', 'service_labs', ['lab_id'], ['id'])
    # ### end Alembic commands ###
