"""added ClassCheckIn model

Revision ID: 1db831388895
Revises: d2402f5085eb
Create Date: 2018-01-07 21:34:20.888604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db831388895'
down_revision = 'd2402f5085eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('late_mins', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_check_in')
    # ### end Alembic commands ###
