"""added canceled_at column and canceled_by_account_id column in ot_record table

Revision ID: 2156d71091a5
Revises: 6b3441ec8619
Create Date: 2022-05-10 13:52:51.555304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2156d71091a5'
down_revision = '6b3441ec8619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ot_record', sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ot_record', sa.Column('canceled_by_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ot_record', 'staff_account', ['canceled_by_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ot_record', type_='foreignkey')
    op.drop_column('ot_record', 'canceled_by_account_id')
    op.drop_column('ot_record', 'canceled_at')
    # ### end Alembic commands ###
