"""added assoc table for the subject area

Revision ID: 21cd1facad8a
Revises: 9abcdd5d2522
Create Date: 2020-11-06 18:17:17.963271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cd1facad8a'
down_revision = '9abcdd5d2522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pub_subjarea_assoc',
    sa.Column('subj_id', sa.String(), nullable=True),
    sa.Column('pub_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pub_id'], ['research_pub.id'], ),
    sa.ForeignKeyConstraint(['subj_id'], ['research_subject_areas.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pub_subjarea_assoc')
    # ### end Alembic commands ###
