"""added new column named pending_days in staff_leave_used_quota table

Revision ID: 24876f38e786
Revises: c446216a7f29
Create Date: 2022-09-30 16:02:46.000292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24876f38e786'
down_revision = 'c446216a7f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_leave_used_quota', sa.Column('pending_days', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_leave_used_quota', 'pending_days')
    # ### end Alembic commands ###
