"""Added meeting_group_assoc Model

Revision ID: 24ab4ea2e161
Revises: e364acd20a44
Create Date: 2024-02-19 14:55:30.232827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ab4ea2e161'
down_revision = 'e364acd20a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_group_assoc',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['staff_group_details.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['meeting_polls.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_group_assoc')
    # ### end Alembic commands ###
