"""Added suggestion column in SoftwareRequestDetail model

Revision ID: 24c74fe18949
Revises: 93a3f2ffef66
Create Date: 2025-04-09 09:54:33.146486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24c74fe18949'
down_revision = '93a3f2ffef66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggestion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_details', schema=None) as batch_op:
        batch_op.drop_column('suggestion')
    # ### end Alembic commands ###
