"""Added phone_number column in ServiceCustomerAddress model

Revision ID: 266db1a3f764
Revises: 094cf4159ba2
Create Date: 2024-11-20 10:05:51.720437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '266db1a3f764'
down_revision = '094cf4159ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_addresses', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
    # ### end Alembic commands ###
