"""Deleted discount column in ServiceQuotationItem model

Revision ID: 26c88b55950b
Revises: 9253523a719c
Create Date: 2025-07-15 09:11:39.664124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26c88b55950b'
down_revision = '9253523a719c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotation_items', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
