"""Deleted budget_source column in ComplaintRepairApproval model

Revision ID: 2b7ad16a47e0
Revises: ee158ac95339
Create Date: 2025-09-08 13:46:59.153537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b7ad16a47e0'
down_revision = 'ee158ac95339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.drop_column('budget_source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
