"""Deleted creator column in ServiceInvoice model

Revision ID: 2b899881cb9f
Revises: 60948e4afe6d
Create Date: 2025-08-17 21:04:47.261649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b899881cb9f'
down_revision = '60948e4afe6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
