"""added staff_id field to the scoresheet model

Revision ID: 2c070188cf09
Revises: a2fb7cad29b6
Create Date: 2023-06-23 10:32:56.718589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c070188cf09'
down_revision = 'a2fb7cad29b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_score_sheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('pa_score_sheets_staff_id_fkey',
                                    'staff_account', ['staff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_score_sheets', schema=None) as batch_op:
        batch_op.drop_constraint('pa_score_sheets_staff_id_fkey', type_='foreignkey')
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###
