"""created seminar_approval_attend_assoc_table for collect list of attend_id in each approval

Revision ID: 2e16f22e6508
Revises: c7a7d46e230b
Create Date: 2022-08-17 15:15:59.266402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e16f22e6508'
down_revision = 'c7a7d46e230b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seminar_approval_attend_assoc',
    sa.Column('attend_id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['staff_seminar_approvals.id'], ),
    sa.ForeignKeyConstraint(['attend_id'], ['staff_seminar_attends.id'], ),
    sa.PrimaryKeyConstraint('attend_id', 'approval_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seminar_approval_attend_assoc')
    # ### end Alembic commands ###
