"""removed some unused columns

Revision ID: 2e37972246c1
Revises: e4218e47a773
Create Date: 2018-01-09 15:06:28.121705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e37972246c1'
down_revision = 'e4218e47a773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'kpis_tactic_id_fkey', 'kpis', type_='foreignkey')
    op.drop_constraint(u'kpis_strategy_id_fkey', 'kpis', type_='foreignkey')
    op.drop_constraint(u'kpis_activity_id_fkey', 'kpis', type_='foreignkey')
    op.drop_constraint(u'kpis_theme_id_fkey', 'kpis', type_='foreignkey')
    op.drop_column('kpis', 'tactic_id')
    op.drop_column('kpis', 'strategy_id')
    op.drop_column('kpis', 'activity_id')
    op.drop_column('kpis', 'theme_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpis', sa.Column('theme_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kpis', sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kpis', sa.Column('strategy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kpis', sa.Column('tactic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'kpis_theme_id_fkey', 'kpis', 'strategy_themes', ['theme_id'], ['id'])
    op.create_foreign_key(u'kpis_activity_id_fkey', 'kpis', 'strategy_activities', ['activity_id'], ['id'])
    op.create_foreign_key(u'kpis_strategy_id_fkey', 'kpis', 'strategies', ['strategy_id'], ['id'])
    op.create_foreign_key(u'kpis_tactic_id_fkey', 'kpis', 'strategy_tactics', ['tactic_id'], ['id'])
    # ### end Alembic commands ###
