"""Added file_name and url column in SoftwareRequestDetail model

Revision ID: 2f1a2a397a84
Revises: af8ce20e1720
Create Date: 2025-03-21 09:56:53.382114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f1a2a397a84'
down_revision = 'af8ce20e1720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_details', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('file_name')
    # ### end Alembic commands ###
