"""added course session model

Revision ID: 30847c27ae5d
Revises: 0f54b9a5a9cd
Create Date: 2021-04-19 06:57:23.565658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30847c27ae5d'
down_revision = '0f54b9a5a9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eduqa_course_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['eduqa_courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eduqa_session_instructor_assoc',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['eduqa_course_instructors.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['eduqa_course_sessions.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eduqa_session_instructor_assoc')
    op.drop_table('eduqa_course_sessions')
    # ### end Alembic commands ###
