"""Added InstrumentsBooking model

Revision ID: 35cf8e617ddf
Revises: a8943833d5e6
Create Date: 2023-03-13 11:18:47.622000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35cf8e617ddf'
down_revision = 'a8943833d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('detail_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('google_event_id', sa.String(length=64), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by'], ['staff_account.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['staff_account.id'], ),
    sa.ForeignKeyConstraint(['detail_id'], ['procurement_details.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['scheduler_room_resources.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['staff_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrument_bookings')
    # ### end Alembic commands ###
