"""

Revision ID: 3702d51a5c1e
Revises: 745c782c2c2e
Create Date: 2025-10-17 14:03:03.387542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3702d51a5c1e'
down_revision = 'e4aef808cd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_seminar_missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_seminar_missions', schema=None) as batch_op:
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###
