"""Added bank name id and relationship in ElectronicReceiptDetail model

Revision ID: 37d31d5ab3ce
Revises: ab9f90df37a9
Create Date: 2023-07-10 11:27:09.479056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d31d5ab3ce'
down_revision = 'ab9f90df37a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electronic_receipt_bank_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_type', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('electronic_receipt_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('electronic_receipt_details_bank_name_id_fkey',
                                    'electronic_receipt_bank_names', ['bank_name_id'], ['id'])
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronic_receipt_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('electronic_receipt_details_bank_name_id_fkey',
                                 type_='foreignkey')
        batch_op.drop_column('bank_name_id')

    op.drop_table('electronic_receipt_bank_names')
    # ### end Alembic commands ###
