"""Added report_comment column in ComplaintPerformanceReport modal

Revision ID: 37fd6f61a1c4
Revises: fd7602389923
Create Date: 2024-06-05 11:56:00.358718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fd6f61a1c4'
down_revision = 'fd7602389923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_performance_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_performance_reports', schema=None) as batch_op:
        batch_op.drop_column('report_comment')

    # ### end Alembic commands ###
