"""Deleted requester_id and requester column in ComplaintRepairApproval model

Revision ID: 385d75da729e
Revises: 78686b8ab1c7
Create Date: 2025-06-30 08:53:24.328359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '385d75da729e'
down_revision = '78686b8ab1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.drop_constraint('complaint_repair_approvals_requester_id_fkey', type_='foreignkey')
        batch_op.drop_column('requester_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('complaint_repair_approvals_requester_id_fkey', 'staff_account', ['requester_id'], ['id'])
    # ### end Alembic commands ###
