"""added api key model

Revision ID: 39af3078b5f6
Revises: 836f496166f1
Create Date: 2018-04-18 05:15:02.176387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39af3078b5f6'
down_revision = '836f496166f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    # ### end Alembic commands ###
