"""Added canceller_id column and canceller column in ComplaintRepairApproval model

Revision ID: 39eaf4dcc36f
Revises: 68190a28874e
Create Date: 2026-05-08 15:23:06.068723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39eaf4dcc36f'
down_revision = '68190a28874e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canceller_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff_account', ['canceller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('canceller_id')
    # ### end Alembic commands ###
