"""Added siriraj_address and salaya_address columns in ServiceSunLab model

Revision ID: 39f9cff2bca0
Revises: 9d5fcb990d7e
Create Date: 2025-11-13 15:56:30.729091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39f9cff2bca0'
down_revision = '9d5fcb990d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_sub_labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siriraj_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('salaya_address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_sub_labs', schema=None) as batch_op:
        batch_op.drop_column('salaya_address')
        batch_op.drop_column('siriraj_address')
    # ### end Alembic commands ###
