"""deleted checked_at column and approval_comment column in table staff_work_from_home_approvals

Revision ID: 39fe5788ad97
Revises: 676c83c070e3
Create Date: 2022-08-01 13:54:51.875273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39fe5788ad97'
down_revision = '676c83c070e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_work_from_home_approvals', 'check_at')
    op.drop_column('staff_work_from_home_approvals', 'approval_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_work_from_home_approvals', sa.Column('approval_comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('staff_work_from_home_approvals', sa.Column('check_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
