"""Added packaging_sealed, container_strength, container_durability, container_damage, info_match, same_production_lot, has_license and has_recipe columns in ServiceSample  model

Revision ID: 3afc004e993c
Revises: 01935e360cc5
Create Date: 2025-07-16 13:44:49.152665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3afc004e993c'
down_revision = '01935e360cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packaging_sealed', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('container_strength', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('container_durability', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('container_damage', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('info_match', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('same_production_lot', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('has_license', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_recipe', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_samples', schema=None) as batch_op:
        batch_op.drop_column('has_recipe')
        batch_op.drop_column('has_license')
        batch_op.drop_column('same_production_lot')
        batch_op.drop_column('info_match')
        batch_op.drop_column('container_damage')
        batch_op.drop_column('container_durability')
        batch_op.drop_column('container_strength')
        batch_op.drop_column('packaging_sealed')
    # ### end Alembic commands ###
