"""created is_approved column in pa_score_sheets table

Revision ID: 3ba643fc1633
Revises: f72367e7307c
Create Date: 2023-06-23 12:44:11.914013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba643fc1633'
down_revision = 'f72367e7307c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_score_sheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_appproved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_score_sheets', schema=None) as batch_op:
        batch_op.drop_column('is_appproved')

    # ### end Alembic commands ###
