"""Added recorder_id and recorder in ComplaintCoordinator model

Revision ID: 3bc72d91200d
Revises: c5378aa0827f
Create Date: 2024-06-12 11:18:35.068023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc72d91200d'
down_revision = 'c5378aa0827f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_coordinators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff_account', ['recorder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_coordinators', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recorder_id')

    # ### end Alembic commands ###
