"""Added SoftwareRequestTeamDiscussion model

Revision ID: 3bfd9e8433f9
Revises: 71a70e0010cf
Create Date: 2025-03-20 15:07:45.761943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bfd9e8433f9'
down_revision = '71a70e0010cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software_request_team_discussions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('discussion', sa.Text(), nullable=True),
    sa.Column('discuss_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['software_request_details.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['staff_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('software_request_team_discussions')
    # ### end Alembic commands ###
