"""Added requirement and phase column in SoftwareRequestTimeline model

Revision ID: 3c2185e5dc12
Revises: 8bfd0d615e7e
Create Date: 2025-04-10 10:47:27.716288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c2185e5dc12'
down_revision = '8bfd0d615e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_timelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phase', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_timelines', schema=None) as batch_op:
        batch_op.drop_column('phase')
        batch_op.drop_column('requirement')
    # ### end Alembic commands ###
