"""added role_id column and relationship in staff_shift_schedule table

Revision ID: 3c3078fcf553
Revises: da8b537ba48a
Create Date: 2022-03-15 17:50:42.249276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3078fcf553'
down_revision = 'da8b537ba48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_shift_schedule', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'staff_shift_schedule', 'staff_shift_role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_shift_schedule', type_='foreignkey')
    op.drop_column('staff_shift_schedule', 'role_id')
    # ### end Alembic commands ###
