"""Added status, payment_date, bill, url, customer_id and customer column in ServicePayment model

Revision ID: 3c684864ea97
Revises: 2a522cca27aa
Create Date: 2024-11-21 09:56:52.593466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c684864ea97'
down_revision = '2a522cca27aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('bill', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'service_customer_infos', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('url')
        batch_op.drop_column('bill')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('status')
    # ### end Alembic commands ###
