"""added more fields to the formative assessment

Revision ID: 3c747ff36ed5
Revises: 59072be28c96
Create Date: 2024-05-29 15:49:03.740568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c747ff36ed5'
down_revision = '59072be28c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eduqa_course_formative_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('assessment_tools', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('end', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('suggestion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eduqa_course_formative_assessments', schema=None) as batch_op:
        batch_op.drop_column('suggestion')
        batch_op.drop_column('end')
        batch_op.drop_column('start')
        batch_op.drop_column('assessment_tools')
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
