"""Added report_language column in ServiceResultItem model

Revision ID: 3d191f7d991f
Revises: 4393e216bae0
Create Date: 2025-07-23 14:53:11.489126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d191f7d991f'
down_revision = '4393e216bae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_result_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_result_items', schema=None) as batch_op:
        batch_op.drop_column('report_language')
    # ### end Alembic commands ###
