"""Added slip column in ServicePayment model

Revision ID: 3f0fcf01bd67
Revises: 77ba7cdf743d
Create Date: 2025-08-21 14:04:01.694711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f0fcf01bd67'
down_revision = '77ba7cdf743d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slip', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.drop_column('slip')
    # ### end Alembic commands ###
