"""Added amount_paid column in ServicePayment model

Revision ID: 417368145a17
Revises: 88efdd5aa1fe
Create Date: 2025-08-21 13:51:37.261750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '417368145a17'
down_revision = '88efdd5aa1fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')
    # ### end Alembic commands ###
