"""added grading schemes

Revision ID: 418e8de9d5b3
Revises: 98eddef7865b
Create Date: 2023-09-02 12:24:19.670569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418e8de9d5b3'
down_revision = '98eddef7865b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eduqa_grading_schemes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eduqa_grading_scheme_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('scheme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scheme_id'], ['eduqa_grading_schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eduqa_grading_scheme_item_criteria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('scheme_item_id', sa.Integer(), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['eduqa_courses.id'], ),
    sa.ForeignKeyConstraint(['scheme_item_id'], ['eduqa_grading_scheme_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eduqa_grading_scheme_item_criteria')
    op.drop_table('eduqa_grading_scheme_items')
    op.drop_table('eduqa_grading_schemes')
    # ### end Alembic commands ###
