"""Added supplier column in ComplaintReapirApproval model

Revision ID: 461362865aa1
Revises: 2b7ad16a47e0
Create Date: 2025-09-08 13:53:49.520195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '461362865aa1'
down_revision = '2b7ad16a47e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.drop_column('supplier')
    # ### end Alembic commands ###
