"""Deleted borrower_id and borrower columns in ComplaintRepairApproval model

Revision ID: 465f97e3abda
Revises: 17a9b39d61aa
Create Date: 2025-07-09 16:06:35.067002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '465f97e3abda'
down_revision = '17a9b39d61aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.drop_constraint('complaint_repair_approvals_borrower_id_fkey', type_='foreignkey')
        batch_op.drop_column('borrower_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('complaint_repair_approvals_borrower_id_fkey', 'staff_account', ['borrower_id'], ['id'])
    # ### end Alembic commands ###
