"""Added end_vote column in MeetingPoll model

Revision ID: 472ac55f9734
Revises: a2a31267f6ec
Create Date: 2025-03-26 11:25:57.486284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '472ac55f9734'
down_revision = 'a2a31267f6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_vote', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_polls', schema=None) as batch_op:
        batch_op.drop_column('end_vote')
    # ### end Alembic commands ###
