"""Deleted short_address column in ServiceSubLab model

Revision ID: 4832dc4bc1ab
Revises: 5ee83ed82ce8
Create Date: 2025-07-08 21:56:51.475597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4832dc4bc1ab'
down_revision = '5ee83ed82ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
