"""added health phyexam model

Revision ID: 4869bb34d7c9
Revises: efde7dbb96de
Create Date: 2018-03-22 16:43:57.125020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4869bb34d7c9'
down_revision = 'efde7dbb96de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_health_phyexam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmscode', sa.String(), nullable=False),
    sa.Column('serviceno', sa.String(), nullable=False),
    sa.Column('servicedate', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('height', sa.Numeric(), nullable=True),
    sa.Column('heartrate', sa.Integer(), nullable=True),
    sa.Column('systolic', sa.Integer(), nullable=True),
    sa.Column('diastolic', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_health_phyexam')
    # ### end Alembic commands ###
