"""removed the view datetime from the receipt model

Revision ID: 4a7543f0633a
Revises: d81c1f9917e3
Create Date: 2021-05-19 22:38:17.621514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a7543f0633a'
down_revision = 'd81c1f9917e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_receive_records', 'viewed_at')
    op.add_column('doc_round_orgs', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_round_orgs', 'finished_at')
    op.add_column('doc_receive_records', sa.Column('viewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
