"""Edited StaffGroupAssociation

Revision ID: 4a92f1c5b43f
Revises: 669a7785ed42
Create Date: 2023-10-24 08:59:08.924383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a92f1c5b43f'
down_revision = '669a7785ed42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_group_associations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('staff_group_associations_group_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'staff_account', ['staff_id'], ['id'])
        batch_op.drop_column('group_id')

    with op.batch_alter_table('staff_group_details', schema=None) as batch_op:
        batch_op.alter_column('appointment_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('expiration_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_group_details', schema=None) as batch_op:
        batch_op.alter_column('expiration_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('appointment_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('staff_group_associations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('staff_group_associations_group_id_fkey', 'staff_account', ['group_id'], ['id'])
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###
