"""created new org_id column in table OtRecord

Revision ID: 4afeb96c20fc
Revises: 544a0b3920c0
Create Date: 2021-12-14 10:55:02.626132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afeb96c20fc'
down_revision = '544a0b3920c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ot_record', sa.Column('orgs_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ot_record', 'orgs', ['orgs_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ot_record', type_='foreignkey')
    op.drop_column('ot_record', 'orgs_id')
    # ### end Alembic commands ###
