"""moved role to detail topic model

Revision ID: 4c65480545e4
Revises: ddbd63a4a42c
Create Date: 2022-10-29 14:15:50.187180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c65480545e4'
down_revision = 'ddbd63a4a42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eduqa_course_session_detail_topics', sa.Column('role', sa.String(), nullable=True))
    op.drop_column('eduqa_course_session_details', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eduqa_course_session_details', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('eduqa_course_session_detail_topics', 'role')
    # ### end Alembic commands ###
