"""created new OtDocumentApproval table for collect ot approval document

Revision ID: 4d7fe256b597
Revises: 4971ecaf6eb3
Create Date: 2021-11-16 20:13:51.301272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7fe256b597'
down_revision = '4971ecaf6eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ot_document_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_no', sa.String(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('orgs_id', sa.Integer(), nullable=True),
    sa.Column('upload_file_url', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('created_staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_staff_id'], ['staff_account.id'], ),
    sa.ForeignKeyConstraint(['orgs_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ot_document_approval')
    # ### end Alembic commands ###
