"""Deleted dean_approved_at, dean_id, dean, mhesi_issued_at, mhesi_issuer_id and mhesi_issuer columns in ServiceInvoice model

Revision ID: 4dba67e45af0
Revises: dc97ea57de85
Create Date: 2025-08-20 23:44:25.163500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4dba67e45af0'
down_revision = 'dc97ea57de85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoices', schema=None) as batch_op:
        batch_op.drop_constraint('service_invoices_mhesi_issuer_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('service_invoices_dean_id_fkey', type_='foreignkey')
        batch_op.drop_column('mhesi_issuer_id')
        batch_op.drop_column('dean_id')
        batch_op.drop_column('dean_approved_at')
        batch_op.drop_column('mhesi_issued_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mhesi_issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dean_approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dean_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mhesi_issuer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('service_invoices_dean_id_fkey', 'staff_account', ['dean_id'], ['id'])
        batch_op.create_foreign_key('service_invoices_mhesi_issuer_id_fkey', 'staff_account', ['mhesi_issuer_id'], ['id'])
    # ### end Alembic commands ###
