"""added learning_plan column in IDPItem table

Revision ID: 4de4128f3767
Revises: bf37d866b1b0
Create Date: 2024-01-10 22:48:03.587123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de4128f3767'
down_revision = 'bf37d866b1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idp_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_plan', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idp_items', schema=None) as batch_op:
        batch_op.drop_column('learning_plan')

    # ### end Alembic commands ###
