"""added course session ID field to the room event model so that a course session can use multiple rooms

Revision ID: 4eab93623f50
Revises: 2b62d675d84d
Create Date: 2023-06-03 15:31:15.728539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eab93623f50'
down_revision = '2b62d675d84d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eduqa_course_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('eduqa_course_sessions_event_id_fkey', type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('scheduler_room_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'eduqa_course_sessions', ['course_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduler_room_reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('course_session_id')

    with op.batch_alter_table('eduqa_course_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('eduqa_course_sessions_event_id_fkey', 'scheduler_room_reservations', ['event_id'], ['id'])

    # ### end Alembic commands ###
