"""added Line Account model for staff

Revision ID: 4eed9877f681
Revises: f2b8516a468d
Create Date: 2020-01-03 15:08:03.358943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eed9877f681'
down_revision = 'f2b8516a468d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_line_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_account_id', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.String(), nullable=False),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['staff_account_id'], ['staff_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_line_account_line_id'), 'staff_line_account', ['line_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_line_account_line_id'), table_name='staff_line_account')
    op.drop_table('staff_line_account')
    # ### end Alembic commands ###
