"""drop committee_id column in pa_score_sheet table

Revision ID: 4eee39a84497
Revises: aa191252f32d
Create Date: 2023-06-16 20:29:56.713210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eee39a84497'
down_revision = 'aa191252f32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_score_sheets', schema=None) as batch_op:
        batch_op.drop_constraint('pa_score_sheets_pa_committee_id_fkey', type_='foreignkey')
        batch_op.drop_column('pa_committee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_score_sheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pa_committee_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pa_score_sheets_pa_committee_id_fkey', 'pa_committees', ['pa_committee_id'], ['id'])

    # ### end Alembic commands ###
