"""Created complaint_record_room_assoc

Revision ID: 4ef22b28ed3c
Revises: 97ab4dad8465
Create Date: 2024-02-06 16:35:01.541641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef22b28ed3c'
down_revision = '97ab4dad8465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_record_room_assoc',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['complaint_records.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['scheduler_room_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.drop_constraint('complaint_records_room_id_fkey', type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('complaint_records_room_id_fkey', 'scheduler_room_resources', ['room_id'], ['id'])

    op.drop_table('complaint_record_room_assoc')
    # ### end Alembic commands ###
