"""Deleted document_address_id, document_address, quotation_address_id and quotation_address columns in ServiceRequst model

Revision ID: 4fc0cfaff3c5
Revises: e5d9d4af20cc
Create Date: 2025-09-12 13:49:21.095795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fc0cfaff3c5'
down_revision = 'e5d9d4af20cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_constraint('service_requests_quotation_address_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('service_requests_document_address_id_fkey', type_='foreignkey')
        batch_op.drop_column('quotation_address_id')
        batch_op.drop_column('document_address_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quotation_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('service_requests_document_address_id_fkey', 'service_customer_addresses', ['document_address_id'], ['id'])
        batch_op.create_foreign_key('service_requests_quotation_address_id_fkey', 'service_customer_addresses', ['quotation_address_id'], ['id'])
    # ### end Alembic commands ###
