"""added creator name field

Revision ID: 50585d469351
Revises: 13dd707bb189
Create Date: 2020-04-01 11:49:54.682263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50585d469351'
down_revision = '13dd707bb189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smartclass_scheduler_online_account_events', sa.Column('creator', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('smartclass_scheduler_online_account_events', 'creator')
    # ### end Alembic commands ###
