"""moved site and service field from booking to slot

Revision ID: 51edfbf74838
Revises: f0de4485287e
Create Date: 2021-02-23 23:26:29.466933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51edfbf74838'
down_revision = 'f0de4485287e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'health_service_bookings_site_id_fkey', 'health_service_bookings', type_='foreignkey')
    op.drop_constraint(u'health_service_bookings_service_id_fkey', 'health_service_bookings', type_='foreignkey')
    op.drop_column('health_service_bookings', 'service_id')
    op.drop_column('health_service_bookings', 'site_id')
    op.add_column('health_service_timeslots', sa.Column('service_id', sa.Integer(), nullable=True))
    op.add_column('health_service_timeslots', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'health_service_timeslots', 'health_service_sites', ['site_id'], ['id'])
    op.create_foreign_key(None, 'health_service_timeslots', 'health_service_services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_service_timeslots', type_='foreignkey')
    op.drop_constraint(None, 'health_service_timeslots', type_='foreignkey')
    op.drop_column('health_service_timeslots', 'site_id')
    op.drop_column('health_service_timeslots', 'service_id')
    op.add_column('health_service_bookings', sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('health_service_bookings', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'health_service_bookings_service_id_fkey', 'health_service_bookings', 'health_service_services', ['service_id'], ['id'])
    op.create_foreign_key(u'health_service_bookings_site_id_fkey', 'health_service_bookings', 'health_service_sites', ['site_id'], ['id'])
    # ### end Alembic commands ###
