"""created new column and relationship named risk_event in KPI table

Revision ID: 521d5032b9d2
Revises: 452fe2719a3d
Create Date: 2024-04-26 14:52:29.554963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521d5032b9d2'
down_revision = '452fe2719a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_event_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'risk_events', ['risk_event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('risk_event_id')

    # ### end Alembic commands ###
