"""added document receive record model

Revision ID: 526bfec2f5b8
Revises: a9804c833dc8
Create Date: 2021-05-18 02:44:24.574477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526bfec2f5b8'
down_revision = 'a9804c833dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_receive_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['doc_documents.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'doc_documents', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'doc_documents', 'comment')
    op.drop_table('doc_receive_records')
    # ### end Alembic commands ###
