"""added PLO model and association tables

Revision ID: 52f878aa277b
Revises: 76818b412714
Create Date: 2023-10-18 09:00:55.805392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f878aa277b'
down_revision = '76818b412714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eduqa_plos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['eduqa_plos.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['eduqa_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eduqa_course_plo_assoc',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['eduqa_courses.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['eduqa_plos.id'], )
    )
    op.create_table('eduqa_clo_plo_assoc',
    sa.Column('clo_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clo_id'], ['eduqa_course_learning_outcomes.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['eduqa_plos.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eduqa_clo_plo_assoc')
    op.drop_table('eduqa_course_plo_assoc')
    op.drop_table('eduqa_plos')
    # ### end Alembic commands ###
