"""Deleted file_attached_at column in ServiceInvoice model

Revision ID: 52fe4d7ebeb0
Revises: d3e4aa83b156
Create Date: 2025-08-21 00:10:41.443025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52fe4d7ebeb0'
down_revision = 'd3e4aa83b156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoices', schema=None) as batch_op:
        batch_op.drop_column('file_attached_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_attached_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
