"""add Table Division and Division Column

Revision ID: 536667d368be
Revises: 15943f1b4409
Create Date: 2022-06-16 21:05:13.169000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536667d368be'
down_revision = '15943f1b4409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comhealth_divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comhealth_department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comhealth_divisions_name'), 'comhealth_divisions', ['name'], unique=False)
    op.add_column(u'comhealth_customers', sa.Column('division_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comhealth_customers', 'comhealth_divisions', ['division_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comhealth_customers', type_='foreignkey')
    op.drop_column(u'comhealth_customers', 'division_id')
    op.drop_index(op.f('ix_comhealth_divisions_name'), table_name='comhealth_divisions')
    op.drop_table('comhealth_divisions')
    # ### end Alembic commands ###
