"""added cancel comment field

Revision ID: 543a6b9e1fdb
Revises: f907b267aae0
Create Date: 2019-12-19 04:48:30.809887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543a6b9e1fdb'
down_revision = 'f907b267aae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comhealth_test_receipts', sa.Column('cancel_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comhealth_test_receipts', 'cancel_comment')
    # ### end Alembic commands ###
