"""Added ServiceOrder model

Revision ID: 5536380c870b
Revises: ec24df57c07c
Create Date: 2024-11-15 14:09:11.628528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5536380c870b'
down_revision = 'ec24df57c07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_no', sa.String(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_account_id', sa.Integer(), nullable=True),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('sample_appointment_id', sa.Integer(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_account_id'], ['service_customer_accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['service_customer_infos.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['service_invoices.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['service_labs.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['service_payments.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['service_quotations.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['service_receipts.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['service_results.id'], ),
    sa.ForeignKeyConstraint(['sample_appointment_id'], ['service_sample_appointments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_orders')
    # ### end Alembic commands ###
