"""comment for customer

Revision ID: 557e7155567b
Revises: fb1cd46e5da5
Create Date: 2023-01-24 13:41:36.635000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557e7155567b'
down_revision = 'fb1cd46e5da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comhealth_customers', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comhealth_customers', 'comment')
    # ### end Alembic commands ###
