"""Added province_id, province, districtid, district, subdistrict_id, subdistict, zipcode_id and zipcode columns in ServiceCustomerAddress model

Revision ID: 564b5b2358a6
Revises: 1cff670f307d
Create Date: 2025-07-15 10:53:51.807707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '564b5b2358a6'
down_revision = '1cff670f307d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('district_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subdistrict_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('zipcode_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'provinces', ['province_id'], ['id'])
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'])
        batch_op.create_foreign_key(None, 'subdistricts', ['subdistrict_id'], ['id'])
        batch_op.create_foreign_key(None, 'zip_codes', ['zipcode_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('zipcode_id')
        batch_op.drop_column('subdistrict_id')
        batch_op.drop_column('district_id')
        batch_op.drop_column('province_id')
    # ### end Alembic commands ###
