"""changed patient id of the order model to foreign key

Revision ID: 564b37502cc1
Revises: 6cd379043799
Create Date: 2018-09-10 04:56:21.042773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564b37502cc1'
down_revision = '6cd379043799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'lis_orders', 'students', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lis_orders', type_='foreignkey')
    # ### end Alembic commands ###
