"""created new column named created_account_id and relatioship in StaffSeminar table

Revision ID: 573655cfeca8
Revises: ef5bec63e536
Create Date: 2024-07-03 10:41:20.593793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573655cfeca8'
down_revision = 'ef5bec63e536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_seminar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff_account', ['staff_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_seminar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('staff_account_id')

    # ### end Alembic commands ###
