"""Added master_id column and secondary column in RoomEvent model

Revision ID: 57c892afa9a5
Revises: af5a2f125e03
Create Date: 2026-03-10 14:37:08.880184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c892afa9a5'
down_revision = 'af5a2f125e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduler_room_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'scheduler_room_reservations', ['master_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduler_room_reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('master_id')
    # ### end Alembic commands ###
