"""added lab test model

Revision ID: 5927f28ccbd4
Revises: 77cf698d0bd3
Create Date: 2018-03-23 15:23:59.717582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5927f28ccbd4'
down_revision = '77cf698d0bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_health_lab_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tcode', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_health_lab_tests')
    # ### end Alembic commands ###
