"""Deleted StaffCostCenter model in staff models

Revision ID: 59cf5336dccb
Revises: 7cee384e6959
Create Date: 2026-06-22 10:36:34.734850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59cf5336dccb'
down_revision = '7cee384e6959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_cost_centers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_cost_centers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cost_center', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secretary_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('head_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['staff_account.id'], name='staff_cost_centers_head_id_fkey'),
    sa.ForeignKeyConstraint(['secretary_id'], ['staff_account.id'], name='staff_cost_centers_secretary_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='staff_cost_centers_pkey')
    )
    # ### end Alembic commands ###
