"""added document's number field

Revision ID: 5a504cd845fa
Revises: 122cd56b1427
Create Date: 2021-05-23 23:18:27.175971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a504cd845fa'
down_revision = '122cd56b1427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_documents', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_documents', 'number')
    # ### end Alembic commands ###
