"""added new column named upload_file_url in staff_seminar table

Revision ID: 5a605f516bfa
Revises: c325fdf7a6a8
Create Date: 2023-05-12 16:31:36.630142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a605f516bfa'
down_revision = 'c325fdf7a6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_seminar', sa.Column('upload_file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_seminar', 'upload_file_url')
    # ### end Alembic commands ###
