"""added scopus ID field

Revision ID: 5a9e6291a59c
Revises: 42f544489b96
Create Date: 2019-03-25 07:05:06.087909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9e6291a59c'
down_revision = '42f544489b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_pub', sa.Column('scopus_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_research_pub_scopus_id'), 'research_pub', ['scopus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_pub_scopus_id'), table_name='research_pub')
    op.drop_column('research_pub', 'scopus_id')
    # ### end Alembic commands ###
