"""added association tables

Revision ID: 5c1efc620972
Revises: 03f8ab98570d
Create Date: 2019-03-19 14:56:32.774461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1efc620972'
down_revision = '03f8ab98570d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comhealth_group_service_assoc',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['comhealth_test_groups.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['comhealth_services.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'service_id')
    )
    op.create_table('comhealth_profile_service_assoc',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['comhealth_test_profiles.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['comhealth_services.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comhealth_profile_service_assoc')
    op.drop_table('comhealth_group_service_assoc')
    # ### end Alembic commands ###
