"""Deleted discount column in ServiceInvoiceItem model

Revision ID: 5c2a11d9ca92
Revises: 05333ba88ad3
Create Date: 2025-07-15 09:20:51.984047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c2a11d9ca92'
down_revision = '05333ba88ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoice_items', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
