"""Added booking_date, amount and format in PurchaseTrackerAccount model

Revision ID: 5cc362572d63
Revises: e7ec574b4333
Create Date: 2022-02-25 16:11:03.240000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc362572d63'
down_revision = 'e7ec574b4333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.add_column('procurement_details', sa.Column('org_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'procurement_details', 'orgs', ['org_id'], ['id'])
    op.add_column('tracker_accounts', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('tracker_accounts', sa.Column('booking_date', sa.Date(), nullable=False))
    op.add_column('tracker_accounts', sa.Column('format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker_accounts', 'format')
    op.drop_column('tracker_accounts', 'booking_date')
    op.drop_column('tracker_accounts', 'amount')
    op.drop_constraint(None, 'procurement_details', type_='foreignkey')
    op.drop_column('procurement_details', 'org_id')
    op.create_table('permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], [u'staff_account.id'], name=u'permissions_staff_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'permissions_pkey')
    )
    op.create_table('roles',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=u'roles_pkey'),
                    sa.UniqueConstraint('name', name=u'roles_name_key')
                    )
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], name=u'user_roles_role_id_fkey', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [u'staff_account.id'], name=u'user_roles_user_id_fkey', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id', name=u'user_roles_pkey')
    )

    # ### end Alembic commands ###
