"""added require_food in staff_seminar table

Revision ID: 5dc53da28b8a
Revises: fe51848fb109
Create Date: 2025-04-09 10:02:05.814265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5dc53da28b8a'
down_revision = 'fe51848fb109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_seminar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_food', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_seminar', schema=None) as batch_op:
        batch_op.drop_column('require_food')
    # ### end Alembic commands ###
