"""added issue text field

Revision ID: 5e2cf8535a8f
Revises: a3178ef64e90
Create Date: 2025-12-04 09:54:22.634242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e2cf8535a8f'
down_revision = 'a3178ef64e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_issues', schema=None) as batch_op:
        batch_op.drop_column('issue')

    # ### end Alembic commands ###
