"""added document_id column in table ot_record

Revision ID: 5f10d9efc7a2
Revises: 457720423400
Create Date: 2022-03-15 15:57:29.091227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f10d9efc7a2'
down_revision = '457720423400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ot_record', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ot_record', 'ot_document_approval', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ot_record', type_='foreignkey')
    op.drop_column('ot_record', 'document_id')
    # ### end Alembic commands ###
