"""added pa_id column in PAFunctionalCompetencyEvaluation table

Revision ID: 608d28a952e7
Revises: badf5865f1f9
Create Date: 2023-11-29 15:45:00.111277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608d28a952e7'
down_revision = 'badf5865f1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_functional_competency_evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pa_agreements', ['pa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_functional_competency_evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pa_id')

    # ### end Alembic commands ###
