"""deleted approval_account_id column in staff_seminar_attends table

Revision ID: 627511d80a77
Revises: d28144668a4a
Create Date: 2022-08-10 13:21:24.843200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627511d80a77'
down_revision = 'd28144668a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'staff_seminar_attends_approver_account_id_fkey', 'staff_seminar_attends', type_='foreignkey')
    op.drop_column('staff_seminar_attends', 'approver_account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_seminar_attends', sa.Column('approver_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'staff_seminar_attends_approver_account_id_fkey', 'staff_seminar_attends', 'staff_account', ['approver_account_id'], ['id'])
    # ### end Alembic commands ###
