"""Added contact column in ServiceSublab model

Revision ID: 6430d4c21b6a
Revises: 7679676c17c7
Create Date: 2025-05-13 09:42:34.600431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6430d4c21b6a'
down_revision = '7679676c17c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_sub_labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_sub_labs', schema=None) as batch_op:
        batch_op.drop_column('contact')
    # ### end Alembic commands ###
