"""Added is_downloaded column in ServiceRequest model

Revision ID: 6455893a9926
Revises: c9cff3e5026d
Create Date: 2025-11-22 13:23:35.302826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6455893a9926'
down_revision = 'c9cff3e5026d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_downloaded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('is_downloaded')
    # ### end Alembic commands ###
