"""Added is_assistant column in ServiceAdmin model

Revision ID: 64d7c7d03aeb
Revises: f5c84651fb21
Create Date: 2025-12-12 16:00:14.245028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64d7c7d03aeb'
down_revision = 'f5c84651fb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_assistant', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_admins', schema=None) as batch_op:
        batch_op.drop_column('is_assistant')
    # ### end Alembic commands ###
