"""digital_signature column in ServiceQuotation model

Revision ID: 661ae4987acf
Revises: de6d3c3f6d07
Create Date: 2025-07-18 21:29:26.567540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '661ae4987acf'
down_revision = 'de6d3c3f6d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('digital_signature', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotations', schema=None) as batch_op:
        batch_op.drop_column('digital_signature')
    # ### end Alembic commands ###
