"""Added reason column in ServiceSample model

Revision ID: 66742b5c592c
Revises: c4235e011e21
Create Date: 2026-07-06 10:25:43.455715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66742b5c592c'
down_revision = 'c4235e011e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_samples', schema=None) as batch_op:
        batch_op.drop_column('reason')
    # ### end Alembic commands ###
