"""Edited StaffGroupDetail

Revision ID: 669a7785ed42
Revises: ccd8f1c279e4
Create Date: 2023-10-16 14:40:23.764230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669a7785ed42'
down_revision = 'ccd8f1c279e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_group_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('official', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_group_details', schema=None) as batch_op:
        batch_op.drop_column('official')
        batch_op.drop_column('public')

    # ### end Alembic commands ###
