"""created KPIStaffAssociation table

Revision ID: 66c519741203
Revises: 529058037082
Create Date: 2023-10-03 16:26:59.797666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c519741203'
down_revision = '529058037082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_staff_association',
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('staff_account_id', sa.Integer(), nullable=False),
    sa.Column('ratio', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.ForeignKeyConstraint(['staff_account_id'], ['staff_account.id'], ),
    sa.PrimaryKeyConstraint('kpi_id', 'staff_account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_staff_association')
    # ### end Alembic commands ###
