"""Added ServiceProduct model

Revision ID: 6a493d61e6d2
Revises: 7455d55a58c2
Create Date: 2024-11-25 16:06:38.435844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a493d61e6d2'
down_revision = '7455d55a58c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('test_method', sa.String(), nullable=True),
    sa.Column('organism', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('carriers', sa.Integer(), nullable=True),
    sa.Column('is_price_not_one_step', sa.Boolean(), nullable=True),
    sa.Column('is_price_one_step', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_products')
    # ### end Alembic commands ###
