"""Added note and convenient_time columns in ServiceSubLab model

Revision ID: 6aabfc284edd
Revises: 46df11dd8b54
Create Date: 2025-07-29 15:37:13.249813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6aabfc284edd'
down_revision = '46df11dd8b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_sub_labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('convenient_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_sub_labs', schema=None) as batch_op:
        batch_op.drop_column('convenient_time')
        batch_op.drop_column('note')
    # ### end Alembic commands ###
