"""Added subtopic_id, and subtopic column in ComplaintRecord

Revision ID: 6ba3d2a578f8
Revises: d502c0b33b9e
Create Date: 2024-02-12 15:37:39.692344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba3d2a578f8'
down_revision = 'd502c0b33b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtopic_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'complaint_sub_topics', ['subtopic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subtopic_id')

    # ### end Alembic commands ###
