"""created kpi_item_id column in pa_score_sheet_items table

Revision ID: 6de5c294a1e7
Revises: d876ce7348c9
Create Date: 2023-06-17 20:09:19.134954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de5c294a1e7'
down_revision = 'd876ce7348c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_score_sheet_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kpi_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pa_kpi_items', ['kpi_item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_score_sheet_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('kpi_item_id')

    # ### end Alembic commands ###
