"""Added url and filename column in ComplaintRecord

Revision ID: 6ec0088ed94b
Revises: ef3098a8fb3a
Create Date: 2024-03-06 15:53:25.049146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec0088ed94b'
down_revision = 'ef3098a8fb3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
