"""added thumbnail url field

Revision ID: 6ec79a0163cd
Revises: 1c2d9f4a8b71
Create Date: 2026-05-30 22:18:14.310988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ec79a0163cd'
down_revision = '1c2d9f4a8b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_survey_results')
    with op.batch_alter_table('procurement_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_thumbnail_url', sa.String(), nullable=True))

    with op.batch_alter_table('scheduler_vehicle_bookings', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_id')
        batch_op.drop_column('google_event_id')

    with op.batch_alter_table('staff_seminar_attends', schema=None) as batch_op:
        batch_op.drop_index('ix_staff_seminar_attends_batch_id')
        batch_op.drop_index('ix_staff_seminar_attends_created_by_id')

    with op.batch_alter_table('staff_seminar_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_staff_seminar_batches_created_by_id')
        batch_op.drop_index('ix_staff_seminar_batches_seminar_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_seminar_batches', schema=None) as batch_op:
        batch_op.create_index('ix_staff_seminar_batches_seminar_id', ['seminar_id'], unique=False)
        batch_op.create_index('ix_staff_seminar_batches_created_by_id', ['created_by_id'], unique=False)

    with op.batch_alter_table('staff_seminar_attends', schema=None) as batch_op:
        batch_op.create_index('ix_staff_seminar_attends_created_by_id', ['created_by_id'], unique=False)
        batch_op.create_index('ix_staff_seminar_attends_batch_id', ['batch_id'], unique=False)

    with op.batch_alter_table('scheduler_vehicle_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_event_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('google_calendar_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('procurement_details', schema=None) as batch_op:
        batch_op.drop_column('image_thumbnail_url')

    op.create_table('food_survey_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('survey_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='food_survey_results_pkey')
    )
    # ### end Alembic commands ###
