"""Added type column in ServiceCustomerAttachment model

Revision ID: 6fc28b5b23ba
Revises: 1355548973a8
Create Date: 2026-09-23 13:52:39.211133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6fc28b5b23ba'
down_revision = '1355548973a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_attachments', schema=None) as batch_op:
        batch_op.drop_column('type')
    # ### end Alembic commands ###
