"""Added reviewed_at column in ComplaintRepair model

Revision ID: 702748721890
Revises: ea6a387ec090
Create Date: 2026-05-25 08:56:41.648383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702748721890'
down_revision = 'ea6a387ec090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repairs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repairs', schema=None) as batch_op:
        batch_op.drop_column('reviewed_at')
    # ### end Alembic commands ###
