"""added citation count to the pub model

Revision ID: 70aac3b05b39
Revises: 0f816514a7b9
Create Date: 2018-05-03 01:02:12.242861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70aac3b05b39'
down_revision = '0f816514a7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_pub', sa.Column('citation_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_pub', 'citation_count')
    # ### end Alembic commands ###
