"""Deleted adder_id, adder column in ServiceCustomer_contact model and deleted customer_id, customer column in ServiceCustomerAddress model

Revision ID: 70fd5646b5e2
Revises: 83ebe75416a2
Create Date: 2024-12-03 11:55:08.853119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70fd5646b5e2'
down_revision = '83ebe75416a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_addresses', schema=None) as batch_op:
        batch_op.drop_constraint('service_customer_addresses_customer_id_fkey', type_='foreignkey')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('service_customer_contacts', schema=None) as batch_op:
        batch_op.drop_constraint('service_customer_contacts_adder_id_fkey', type_='foreignkey')
        batch_op.drop_column('adder_id')

    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'service_customer_accounts', ['customer_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('customer_account_id')

    with op.batch_alter_table('service_customer_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adder_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('service_customer_contacts_adder_id_fkey', 'service_customer_infos', ['adder_id'], ['id'])

    with op.batch_alter_table('service_customer_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('service_customer_addresses_customer_id_fkey', 'service_customer_infos', ['customer_id'], ['id'])
    # ### end Alembic commands ###
