"""added a model to allow circulating docs to multiple orgs

Revision ID: 7248a19842ff
Revises: fadf69ad4b20
Create Date: 2021-05-19 20:20:42.808429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7248a19842ff'
down_revision = 'fadf69ad4b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_round_orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['doc_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'doc_documents', sa.Column('round_org_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'doc_documents_round_id_fkey', 'doc_documents', type_='foreignkey')
    op.create_foreign_key(None, 'doc_documents', 'doc_round_orgs', ['round_org_id'], ['id'])
    op.drop_column(u'doc_documents', 'round_id')
    op.drop_column(u'doc_rounds', 'submitted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'doc_rounds', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column(u'doc_documents', sa.Column('round_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'doc_documents', type_='foreignkey')
    op.create_foreign_key(u'doc_documents_round_id_fkey', 'doc_documents', 'doc_rounds', ['round_id'], ['id'])
    op.drop_column(u'doc_documents', 'round_org_id')
    op.drop_table('doc_round_orgs')
    # ### end Alembic commands ###
