"""Added discount column in ServiceInvoiceItem model

Revision ID: 73eb9e2e71f6
Revises: 5c2a11d9ca92
Create Date: 2025-07-15 09:37:31.767144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73eb9e2e71f6'
down_revision = '5c2a11d9ca92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoice_items', schema=None) as batch_op:
        batch_op.drop_column('discount')
    # ### end Alembic commands ###
