"""Deleted slip column in ServicePayment model

Revision ID: 77ba7cdf743d
Revises: 417368145a17
Create Date: 2025-08-21 13:58:27.860517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77ba7cdf743d'
down_revision = '417368145a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.drop_column('slip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slip', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
