"""added one to one relationship to services and phyexams

Revision ID: 77cf698d0bd3
Revises: 91989b7f3c9b
Create Date: 2018-03-22 18:04:45.850604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cf698d0bd3'
down_revision = '91989b7f3c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_health_services', sa.Column('phyexam_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'food_health_services', 'food_health_phyexam', ['phyexam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food_health_services', type_='foreignkey')
    op.drop_column('food_health_services', 'phyexam_id')
    # ### end Alembic commands ###
