"""added updated date and time to the record model

Revision ID: 782214ea363f
Revises: ac1b240a4510
Create Date: 2019-03-31 03:48:04.627071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782214ea363f'
down_revision = 'ac1b240a4510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comhealth_test_records', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comhealth_test_records', 'updated_at')
    # ### end Alembic commands ###
