"""Added record_id and record column in ComplaintRepairApproval model

Revision ID: 78686b8ab1c7
Revises: 4976f6a6b920
Create Date: 2025-06-29 18:27:54.775921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78686b8ab1c7'
down_revision = '4976f6a6b920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'complaint_records', ['record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('record_id')
    # ### end Alembic commands ###
