"""Added room id column and relationship in ComplaintRecord model

Revision ID: 797ef57895b3
Revises: 0fb117c95e5c
Create Date: 2023-08-25 15:20:39.946221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797ef57895b3'
down_revision = '0fb117c95e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'scheduler_room_resources', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
