"""Added is_rescheduled column, rejecter_id column and rejecter column in ServiceSample model

Revision ID: 7a50a69df79d
Revises: 66742b5c592c
Create Date: 2026-07-06 10:48:30.216770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a50a69df79d'
down_revision = '66742b5c592c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rescheduled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('rejecter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff_account', ['rejecter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_samples', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rejecter_id')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('is_rescheduled')
    # ### end Alembic commands ###
