"""added asset item model

Revision ID: 7ad290846e99
Revises: cf575b5b3174
Create Date: 2019-01-03 05:21:47.561067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad290846e99'
down_revision = 'cf575b5b3174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.Column('retired_at', sa.Date(), nullable=True),
    sa.Column('group_id', sa.String(length=2), nullable=False),
    sa.Column('class_id', sa.String(length=2), nullable=False),
    sa.Column('type_id', sa.String(length=3), nullable=False),
    sa.Column('desc_id', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_items')
    # ### end Alembic commands ###
