"""added app user ID to the bookings model

Revision ID: 7d048ab06595
Revises: 21b4337e1b94
Create Date: 2021-03-03 06:11:31.088757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d048ab06595'
down_revision = '21b4337e1b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_service_bookings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'health_service_bookings', 'health_service_app_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_service_bookings', type_='foreignkey')
    op.drop_column('health_service_bookings', 'user_id')
    # ### end Alembic commands ###
