"""created new table named HeadOrg

Revision ID: 7dc16e697fa4
Revises: c62da24df658
Create Date: 2023-03-01 09:01:51.319946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc16e697fa4'
down_revision = 'c62da24df658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('head_orgs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head_account_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['head_account_id'], ['staff_account.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('head_orgs')
    # ### end Alembic commands ###
