"""Deleted phase column in SoftwareRequestTimeline model of software_request model

Revision ID: 80096702a440
Revises: 4c6ce3635970
Create Date: 2026-04-24 14:51:19.514693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80096702a440'
down_revision = '4c6ce3635970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_timelines', schema=None) as batch_op:
        batch_op.drop_column('phase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_timelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
