"""added is_lower_level and is_middle_level columns in StaffLeaveApprover table

Revision ID: 80208cde44a6
Revises: 2b7ae04043f0
Create Date: 2026-05-15 21:01:09.721976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80208cde44a6'
down_revision = '2b7ae04043f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_leave_approvers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lower_level', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_middle_level', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_leave_approvers', schema=None) as batch_op:
        batch_op.drop_column('is_middle_level')
        batch_op.drop_column('is_lower_level')
    # ### end Alembic commands ###
