"""replaced pdpa services with core services

Revision ID: 8099ea86b349
Revises: 4c21031c23e4
Create Date: 2022-05-22 23:38:42.422839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8099ea86b349'
down_revision = '4c21031c23e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdpa_requests', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pdpa_requests', 'db_core_services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pdpa_requests', type_='foreignkey')
    op.drop_column('pdpa_requests', 'service_id')
    # ### end Alembic commands ###
