"""Added remark column in ServiceFinalResultItemReversion model

Revision ID: 818d59a788fd
Revises: 7994deb166b4
Create Date: 2026-07-15 13:08:21.978447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '818d59a788fd'
down_revision = '7994deb166b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_final_result_item_reversions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_final_result_item_reversions', schema=None) as batch_op:
        batch_op.drop_column('remark')
    # ### end Alembic commands ###
