"""Added record_id column and record column in ComplaintSparePart model

Revision ID: 833e832d851f
Revises: 21863d9805df
Create Date: 2026-06-20 14:52:37.910386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '833e832d851f'
down_revision = '21863d9805df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_spare_parts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'complaint_records', ['record_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_spare_parts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('record_id')
    # ### end Alembic commands ###
