"""Add Floor field model

Revision ID: 8563cc311a01
Revises: 2b76b4e1b66b
Create Date: 2021-11-11 10:32:15.382000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8563cc311a01'
down_revision = '2b76b4e1b66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement_details', 'location')
    op.add_column('scheduler_room_resources', sa.Column('floor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_room_resources', 'floor')
    op.add_column('procurement_details', sa.Column('location', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
