"""added reimbursable field

Revision ID: 865c846872f4
Revises: 7bc55b9a27e5
Create Date: 2023-08-16 14:46:30.457183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865c846872f4'
down_revision = '7bc55b9a27e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comhealth_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reimbursable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comhealth_tests', schema=None) as batch_op:
        batch_op.drop_column('reimbursable')

    # ### end Alembic commands ###
