"""added topic form for detail topics

Revision ID: 8954f72f01fa
Revises: 92968b8d2254
Create Date: 2022-10-29 10:40:09.376939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8954f72f01fa'
down_revision = '92968b8d2254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eduqa_course_session_detail_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_detail_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_detail_id'], ['eduqa_course_session_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'eduqa_course_session_details', 'topic')
    op.drop_column(u'eduqa_course_session_details', 'detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'eduqa_course_session_details', sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(u'eduqa_course_session_details', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('eduqa_course_session_detail_topics')
    # ### end Alembic commands ###
