"""created ot_round_request table in ot folder

Revision ID: 895e42250d05
Revises: 95e152378d9f
Create Date: 2022-03-22 16:05:28.409957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895e42250d05'
down_revision = '95e152378d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ot_round_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_account_id', sa.Integer(), nullable=True),
    sa.Column('approval_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_by_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approval_by_account_id'], ['staff_account.id'], ),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['staff_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'ot_record', sa.Column('round_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ot_record', 'ot_round_request', ['round_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ot_record', type_='foreignkey')
    op.drop_column(u'ot_record', 'round_id')
    op.drop_table('ot_round_request')
    # ### end Alembic commands ###
