"""added cashier model

Revision ID: 8985b2bac8c3
Revises: c013ff41dbee
Create Date: 2019-12-02 15:47:18.590295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8985b2bac8c3'
down_revision = 'c013ff41dbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comhealth_cashier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comhealth_cashier_firstname'), 'comhealth_cashier', ['firstname'], unique=False)
    op.create_index(op.f('ix_comhealth_cashier_lastname'), 'comhealth_cashier', ['lastname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comhealth_cashier_lastname'), table_name='comhealth_cashier')
    op.drop_index(op.f('ix_comhealth_cashier_firstname'), table_name='comhealth_cashier')
    op.drop_table('comhealth_cashier')
    # ### end Alembic commands ###
