"""added new column round_no in ot_round_request table

Revision ID: 8d60980b4a3a
Revises: 1f65b7a02e90
Create Date: 2022-04-29 21:36:42.797210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d60980b4a3a'
down_revision = '1f65b7a02e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ot_round_request', sa.Column('round_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ot_round_request', 'round_no')
    # ### end Alembic commands ###
