"""added staff id field to time slot model

Revision ID: 8e7e2c7c8b8c
Revises: 46d778b15b6d
Create Date: 2021-02-24 00:12:31.840143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7e2c7c8b8c'
down_revision = '46d778b15b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_service_timeslots', sa.Column('staff_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'health_service_timeslots', 'staff_account', ['staff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_service_timeslots', type_='foreignkey')
    op.drop_column('health_service_timeslots', 'staff_id')
    # ### end Alembic commands ###
