"""added rate field to timeslot

Revision ID: 8f8e8544941d
Revises: 4330faef9662
Create Date: 2023-09-11 15:37:10.357327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8e8544941d'
down_revision = '4330faef9662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ot_compensation_rate_time_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ot_compensation_rate_time_slots', schema=None) as batch_op:
        batch_op.drop_column('rate')

    # ### end Alembic commands ###
