"""Added ComplaintRecordStatusAssociation model

Revision ID: 8fb581d37414
Revises: ddc0b802818b
Create Date: 2026-05-15 10:58:49.358588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb581d37414'
down_revision = 'ddc0b802818b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_record_status_associations',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['complaint_records.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['complaint_statuses.id'], ),
    sa.PrimaryKeyConstraint('record_id', 'status_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint_record_status_associations')
    # ### end Alembic commands ###
