"""added a field for the market to which the  produce from farm delivered to

Revision ID: 8fd81d779c83
Revises: ddfa18de9463
Create Date: 2018-07-16 09:31:57.543467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd81d779c83'
down_revision = 'ddfa18de9463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm_to_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('market_detail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_detail_id'], ['market_details.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'food_farms', sa.Column('market_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'food_farms', 'farm_to_markets', ['market_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food_farms', type_='foreignkey')
    op.drop_column(u'food_farms', 'market_id')
    op.drop_table('farm_to_markets')
    op.drop_table('market_types')
    op.drop_table('market_details')
    # ### end Alembic commands ###
