"""added well types and sizes to the farm model

Revision ID: 9137771d54bb
Revises: be14f358e96b
Create Date: 2018-07-16 08:51:54.620545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9137771d54bb'
down_revision = 'be14f358e96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('well_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('well_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'food_farms', sa.Column('well_size_id', sa.Integer(), nullable=True))
    op.add_column(u'food_farms', sa.Column('well_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'food_farms', 'well_types', ['well_type_id'], ['id'])
    op.create_foreign_key(None, 'food_farms', 'well_sizes', ['well_size_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food_farms', type_='foreignkey')
    op.drop_constraint(None, 'food_farms', type_='foreignkey')
    op.drop_column(u'food_farms', 'well_type_id')
    op.drop_column(u'food_farms', 'well_size_id')
    op.drop_table('well_types')
    op.drop_table('well_sizes')
    # ### end Alembic commands ###
