"""added health services model

Revision ID: 91989b7f3c9b
Revises: 4869bb34d7c9
Create Date: 2018-03-22 17:31:23.293609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91989b7f3c9b'
down_revision = '4869bb34d7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_health_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmscode', sa.String(), nullable=False),
    sa.Column('serviceno', sa.String(), nullable=False),
    sa.Column('servicedate', sa.DateTime(), nullable=True),
    sa.Column('health_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['health_person_id'], ['food_health_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_health_services')
    # ### end Alembic commands ###
