"""added column after hour in table StaffLeaveRequest

Revision ID: 9231935211aa
Revises: 57407308c85f
Create Date: 2020-08-13 13:30:19.599407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9231935211aa'
down_revision = '57407308c85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_leave_requests', sa.Column('after_hour', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_leave_requests', 'after_hour')
    # ### end Alembic commands ###
