"""Deleted convenient_time column in ServiceSubLab model

Revision ID: 92d84bf01862
Revises: 6aabfc284edd
Create Date: 2025-07-29 16:06:08.937199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92d84bf01862'
down_revision = '6aabfc284edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ##
    with op.batch_alter_table('service_sub_labs', schema=None) as batch_op:
        batch_op.drop_column('convenient_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_sub_labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('convenient_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
