"""Deleted discount column in ServiceQuotation model

Revision ID: 940e2b256ecb
Revises: 97ec8548f844
Create Date: 2025-05-26 10:47:12.349200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '940e2b256ecb'
down_revision = '97ec8548f844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotations', schema=None) as batch_op:
        batch_op.drop_column('discount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
