"""Added column book, number, receipt date, disbursement method, financial year, cost center, internal order, parcel inspector name, approve disbursement, total money, advance name, org in purchase tracker forms

Revision ID: 942184eddf89
Revises: 792e384fe549
Create Date: 2022-07-01 14:58:02.583000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942184eddf89'
down_revision = '792e384fe549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_forms', sa.Column('advance_name', sa.String(), nullable=True))
    op.add_column('tracker_forms', sa.Column('approve_disbursement', sa.String(), nullable=True))
    op.add_column('tracker_forms', sa.Column('book', sa.String(), nullable=True))
    op.add_column('tracker_forms', sa.Column('cost_center', sa.String(), nullable=True))
    op.add_column('tracker_forms', sa.Column('disbursement_method', sa.String(), nullable=True))
    op.add_column('tracker_forms', sa.Column('financial_year', sa.String(), nullable=True))
    op.add_column('tracker_forms', sa.Column('internal_order', sa.String(), nullable=True))
    op.add_column('tracker_forms', sa.Column('number', sa.String(), nullable=True))
    op.add_column('tracker_forms', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('tracker_forms', sa.Column('parcel_inspector_name', sa.String(), nullable=True))
    op.add_column('tracker_forms', sa.Column('receipt_date', sa.Date(), nullable=True))
    op.add_column('tracker_forms', sa.Column('total_money', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tracker_forms', 'orgs', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracker_forms', type_='foreignkey')
    op.drop_column('tracker_forms', 'total_money')
    op.drop_column('tracker_forms', 'receipt_date')
    op.drop_column('tracker_forms', 'parcel_inspector_name')
    op.drop_column('tracker_forms', 'org_id')
    op.drop_column('tracker_forms', 'number')
    op.drop_column('tracker_forms', 'internal_order')
    op.drop_column('tracker_forms', 'financial_year')
    op.drop_column('tracker_forms', 'disbursement_method')
    op.drop_column('tracker_forms', 'cost_center')
    op.drop_column('tracker_forms', 'book')
    op.drop_column('tracker_forms', 'approve_disbursement')
    op.drop_column('tracker_forms', 'advance_name')
    # ### end Alembic commands ###
