"""Added owner_id column and owner column in ComplaintRepairApproval model

Revision ID: 976459b74ede
Revises: 00266efb05f4
Create Date: 2026-05-06 09:07:32.249475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976459b74ede'
down_revision = '00266efb05f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff_account', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')
    # ### end Alembic commands ###
