"""added course session duration and topic coverage fields

Revision ID: 97c358a204b1
Revises: a594353497d2
Create Date: 2024-05-29 10:20:11.726114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c358a204b1'
down_revision = 'a594353497d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eduqa_course_session_topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_covered', sa.Boolean(), nullable=True))

    with op.batch_alter_table('eduqa_course_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eduqa_course_sessions', schema=None) as batch_op:
        batch_op.drop_column('duration')

    with op.batch_alter_table('eduqa_course_session_topics', schema=None) as batch_op:
        batch_op.drop_column('is_covered')

    # ### end Alembic commands ###
