"""Added discount column in ServiceInvoiceItem model

Revision ID: 97ec8548f844
Revises: 03931505996e
Create Date: 2025-05-26 09:23:08.886026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97ec8548f844'
down_revision = '03931505996e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoice_items', schema=None) as batch_op:
        batch_op.drop_column('discount')
    # ### end Alembic commands ###
