"""changed created at column name to updated at

Revision ID: 9816f539c85a
Revises: 99b30b49b16d
Create Date: 2025-12-11 14:33:16.179263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9816f539c85a'
down_revision = '99b30b49b16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_issues', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
    # ### end Alembic commands ###
