"""Added quotation_status column in ServiceRequest model

Revision ID: 987a760faf5a
Revises: 32a10a8b5076
Create Date: 2024-11-08 14:03:51.782206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '987a760faf5a'
down_revision = '32a10a8b5076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('quotation_status')
    # ### end Alembic commands ###
