"""Removed nullable is false in name and available column in ProcurementDetail model

Revision ID: 9b4eba0ef668
Revises: 06162c45baa5
Create Date: 2022-09-28 14:06:24.396000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4eba0ef668'
down_revision = '06162c45baa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'procurement_details', 'available',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column(u'procurement_details', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'procurement_details', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column(u'procurement_details', 'available',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
