"""Edited MeetingPollItem

Revision ID: 9bd1dea322f4
Revises: 9fb4ab9e6153
Create Date: 2023-11-29 08:49:23.814098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bd1dea322f4'
down_revision = '9fb4ab9e6153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_poll_items', schema=None) as batch_op:
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_poll_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
