"""Deleted is_cancel column in ServiceQuotation model

Revision ID: 9c7fabc08979
Revises: 056efb6e56fc
Create Date: 2025-02-04 11:48:05.903865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c7fabc08979'
down_revision = '056efb6e56fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotations', schema=None) as batch_op:
        batch_op.drop_column('is_cancel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancel', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
