"""created document_no column in staff_seminar_attends table and deleted seminar_approval_attend_assoc_table

Revision ID: 9d3ce8a098a6
Revises: d530eee56fa5
Create Date: 2022-08-31 16:14:16.054879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3ce8a098a6'
down_revision = 'd530eee56fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seminar_approval_attend_assoc')
    op.add_column('staff_seminar_attends', sa.Column('document_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_seminar_attends', 'document_no')
    op.create_table('seminar_approval_attend_assoc',
    sa.Column('attend_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approval_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], [u'staff_seminar_approvals.id'], name=u'seminar_approval_attend_assoc_approval_id_fkey'),
    sa.ForeignKeyConstraint(['attend_id'], [u'staff_seminar_attends.id'], name=u'seminar_approval_attend_assoc_attend_id_fkey'),
    sa.PrimaryKeyConstraint('attend_id', 'approval_id', name=u'seminar_approval_attend_assoc_pkey')
    )
    # ### end Alembic commands ###
