"""Added customer_account_id and customer_account column in ServiceCustomerAddress model

Revision ID: 9d8c524905fb
Revises: 44d5d5a3a6d0
Create Date: 2024-12-04 13:53:04.209418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d8c524905fb'
down_revision = '44d5d5a3a6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_addresses', schema=None) as batch_op:
        batch_op.drop_constraint('service_customer_addresses_customer_account_id_fkey', type_='foreignkey')
        batch_op.drop_column('customer_account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('service_customer_addresses_customer_account_id_fkey', 'service_customer_accounts', ['customer_account_id'], ['id'])
    # ### end Alembic commands ###
