"""added on create field to the model

Revision ID: 9ecf4046bc30
Revises: 91260d2152e7
Create Date: 2018-04-18 06:37:21.411977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecf4046bc30'
down_revision = '91260d2152e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_pub', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_pub', 'created_at')
    # ### end Alembic commands ###
