"""Added lab column in ServiceNumberID model

Revision ID: 9ed79d38f5cb
Revises: 1da59748b8b4
Create Date: 2025-02-04 09:07:47.591251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ed79d38f5cb'
down_revision = '1da59748b8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
