"""added new column (file_name) into table ot_payment_announce

Revision ID: 9f44a49274c5
Revises: c7028e279d51
Create Date: 2021-11-03 14:36:15.034406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f44a49274c5'
down_revision = 'c7028e279d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ot_payment_announce', sa.Column('file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ot_payment_announce', 'file_name')
    # ### end Alembic commands ###
