"""Edited MeetingEvent

Revision ID: 9fb4ab9e6153
Revises: e090c41f6d34
Create Date: 2023-11-17 15:20:50.637039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb4ab9e6153'
down_revision = 'e090c41f6d34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poll_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'meeting_polls', ['poll_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('poll_id')

    # ### end Alembic commands ###
