"""created relationship between staff_position table and staff_personal_info table and added position_id column in staff_posersonal_info table

Revision ID: a00c66f2b9b2
Revises: f20d4af673ac
Create Date: 2022-07-08 13:00:01.624803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00c66f2b9b2'
down_revision = 'f20d4af673ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_personal_info', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'staff_personal_info', 'staff_positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_personal_info', type_='foreignkey')
    op.drop_column('staff_personal_info', 'position_id')
    # ### end Alembic commands ###
