"""updated staff academic position model

Revision ID: a2ac5b89ff68
Revises: 92253b02cf13
Create Date: 2019-07-03 07:39:29.208783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ac5b89ff68'
down_revision = '92253b02cf13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_academic_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname_th', sa.String(), nullable=False),
    sa.Column('shortname_th', sa.String(), nullable=False),
    sa.Column('fullname_en', sa.String(), nullable=False),
    sa.Column('shortname_en', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'staff_personal_info', sa.Column('academic_position_id', sa.Integer(), nullable=True))
    op.add_column(u'staff_personal_info', sa.Column('orgs_id', sa.Integer(), nullable=True))
    op.add_column(u'staff_personal_info', sa.Column('th_firstname',
                                                    sa.String(), nullable=False))
    op.add_column(u'staff_personal_info', sa.Column('th_lastname', sa.String(),
                                                    nullable=False))
    op.create_foreign_key(None, 'staff_personal_info', 'staff_academic_position', ['academic_position_id'], ['id'])
    op.create_foreign_key(None, 'staff_personal_info', 'orgs', ['orgs_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_personal_info', type_='foreignkey')
    op.drop_constraint(None, 'staff_personal_info', type_='foreignkey')
    op.drop_column(u'staff_personal_info', 'th_lastname')
    op.drop_column(u'staff_personal_info', 'th_firstname')
    op.drop_column(u'staff_personal_info', 'orgs_id')
    op.drop_column(u'staff_personal_info', 'academic_position_id')
    op.drop_table('staff_academic_position')
    # ### end Alembic commands ###
