"""created new staff_job_positions table in staff

Revision ID: a2e11a232152
Revises: b713d97a7676
Create Date: 2023-07-18 12:06:27.703065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e11a232152'
down_revision = 'b713d97a7676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_job_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('en_title', sa.String(), nullable=True),
    sa.Column('th_title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_job_positions')
    # ### end Alembic commands ###
