"""added performance_score and competency_score columns in pa_agreements table

Revision ID: a2fdb02cb417
Revises: 0c292310d41a
Create Date: 2023-07-03 13:55:03.621350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fdb02cb417'
down_revision = '0c292310d41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_agreements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performance_score', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('competency_score', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_agreements', schema=None) as batch_op:
        batch_op.drop_column('competency_score')
        batch_op.drop_column('performance_score')

    # ### end Alembic commands ###
