"""Deleted issue_auotation and is_paid column in ServiceRecord model

Revision ID: a30699da8620
Revises: 364a43bdfdae
Create Date: 2025-01-06 11:33:02.585046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a30699da8620'
down_revision = '364a43bdfdae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('issue_quotation')
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('issue_quotation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
