"""Deleted CostCenterAutority model

Revision ID: a31d32277969
Revises: c9895f20cccb
Create Date: 2026-06-22 10:17:51.331048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a31d32277969'
down_revision = 'c9895f20cccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_center_authorities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_center_authorities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cost_center', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secretary_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('head_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['head_id'], ['staff_account.id'], name='cost_center_authorities_head_id_fkey'),
    sa.ForeignKeyConstraint(['secretary_id'], ['staff_account.id'], name='cost_center_authorities_secretary_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cost_center_authorities_pkey')
    )
    # ### end Alembic commands ###
