"""Added Information ProcurementDetail Model

Revision ID: a5b645a96df2
Revises: 65863e47e914
Create Date: 2021-12-30 10:59:19.895000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b645a96df2'
down_revision = '65863e47e914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_details', sa.Column('bought_by', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('budget_year', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('building', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('department', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('document_no', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('erp_code', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('floor', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('guarantee', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('procurement_details', sa.Column('price', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('procurement_no', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('purchasing_type', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('quantity', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('received_date', sa.Date(), nullable=True))
    op.add_column('procurement_details', sa.Column('registration_no', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('responsible_person', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('room', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('serial_no', sa.String(), nullable=True))
    op.add_column('procurement_details', sa.Column('university_no', sa.String(), nullable=True))
    op.drop_column('procurement_details', 'code')
    op.drop_column('procurement_details', 'list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_details', sa.Column('list', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('procurement_details', sa.Column('code', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('procurement_details', 'university_no')
    op.drop_column('procurement_details', 'serial_no')
    op.drop_column('procurement_details', 'room')
    op.drop_column('procurement_details', 'responsible_person')
    op.drop_column('procurement_details', 'registration_no')
    op.drop_column('procurement_details', 'received_date')
    op.drop_column('procurement_details', 'quantity')
    op.drop_column('procurement_details', 'purchasing_type')
    op.drop_column('procurement_details', 'procurement_no')
    op.drop_column('procurement_details', 'price')
    op.drop_column('procurement_details', 'name')
    op.drop_column('procurement_details', 'guarantee')
    op.drop_column('procurement_details', 'floor')
    op.drop_column('procurement_details', 'erp_code')
    op.drop_column('procurement_details', 'document_no')
    op.drop_column('procurement_details', 'department')
    op.drop_column('procurement_details', 'building')
    op.drop_column('procurement_details', 'budget_year')
    op.drop_column('procurement_details', 'bought_by')
    # ### end Alembic commands ###
