"""added significance and suggestion fields

Revision ID: a6eea0015f83
Revises: d1196e9d8d8c
Create Date: 2024-05-29 12:13:45.181761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6eea0015f83'
down_revision = 'd1196e9d8d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eduqa_course_session_topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('significance', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('suggestion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eduqa_course_session_topics', schema=None) as batch_op:
        batch_op.drop_column('suggestion')
        batch_op.drop_column('significance')

    # ### end Alembic commands ###
