"""Deleted ServiceCustomerOrganization model

Revision ID: a8eb8932054d
Revises: 165ba4716aed
Create Date: 2025-02-05 10:39:07.247554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8eb8932054d'
down_revision = '165ba4716aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_customer_organizations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_customer_organizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['staff_account.id'], name='service_customer_organizations_admin_id_fkey'),
    sa.ForeignKeyConstraint(['creator_id'], ['service_customer_infos.id'], name='service_customer_organizations_creator_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_customer_organizations_pkey')
    )
    # ### end Alembic commands ###
