"""Added req_edit_at, edit_requester_id, edit_requester, not and is_edited columns in ServiceResultItem model

Revision ID: aa042ff5328b
Revises: 8862fda5097a
Create Date: 2025-11-24 14:59:42.798296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa042ff5328b'
down_revision = '8862fda5097a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_result_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('req_edit_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('edit_requester_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'service_customer_accounts', ['edit_requester_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_result_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_edited')
        batch_op.drop_column('note')
        batch_op.drop_column('edit_requester_id')
        batch_op.drop_column('req_edit_at')
    # ### end Alembic commands ###
