"""added some more fields to the requests

Revision ID: aa3b02b26dc3
Revises: 463c6236fa58
Create Date: 2022-05-22 23:02:56.109768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3b02b26dc3'
down_revision = '463c6236fa58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdpa_requests', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pdpa_requests', sa.Column('decision', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdpa_requests', 'decision')
    op.drop_column('pdpa_requests', 'approved_at')
    # ### end Alembic commands ###
