"""Deleted ComplaintRecodTagAssociation model

Revision ID: aab4940fe34a
Revises: 581e2166954f
Create Date: 2024-05-16 11:46:52.689019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab4940fe34a'
down_revision = '581e2166954f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint_record_tag_associations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_record_tag_associations',
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['complaint_records.id'], name='complaint_record_tag_associations_record_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['complaint_tags.id'], name='complaint_record_tag_associations_tag_id_fkey'),
    sa.PrimaryKeyConstraint('tag_id', 'record_id', name='complaint_record_tag_associations_pkey')
    )
    # ### end Alembic commands ###
