"""created new 3 columns in OtRecord (total_hours, total_minutes and amount_paid columns)

Revision ID: ab92db7ccb8e
Revises: 2156d71091a5
Create Date: 2022-05-12 17:47:00.194292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab92db7ccb8e'
down_revision = '2156d71091a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ot_record', sa.Column('amount_paid', sa.Float(), nullable=True))
    op.add_column('ot_record', sa.Column('total_hours', sa.Integer(), nullable=True))
    op.add_column('ot_record', sa.Column('total_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ot_record', 'total_minutes')
    op.drop_column('ot_record', 'total_hours')
    op.drop_column('ot_record', 'amount_paid')
    # ### end Alembic commands ###
