"""Changed type string to text of item in ElectronicReceiptItem model

Revision ID: ab9f90df37a9
Revises: e8d2836a1c0e
Create Date: 2023-07-07 15:27:24.819399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9f90df37a9'
down_revision = 'e8d2836a1c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronic_receipt_items', schema=None) as batch_op:
        batch_op.alter_column('item',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronic_receipt_items', schema=None) as batch_op:
        batch_op.alter_column('item',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
