"""added doc url field

Revision ID: abddf0285b1a
Revises: 3ebcc27f5e58
Create Date: 2023-07-07 10:50:43.751978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abddf0285b1a'
down_revision = '3ebcc27f5e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_events', schema=None) as batch_op:
        batch_op.drop_column('doc_url')

    # ### end Alembic commands ###
