"""Added document_address_id and document_address columns in ServiceRequest model

Revision ID: ad1dc192b624
Revises: e17320daf67d
Create Date: 2025-09-12 14:35:23.932110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad1dc192b624'
down_revision = 'e17320daf67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_address_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'service_customer_addresses', ['document_address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('document_address_id')
    # ### end Alembic commands ###
