"""created idp_item_seminar_attend_assoc_table table

Revision ID: b1ddddbc52e4
Revises: d59585525b55
Create Date: 2026-01-12 16:59:14.450595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1ddddbc52e4'
down_revision = 'd59585525b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idp_item_seminar_attend_assoc',
    sa.Column('idp_item_id', sa.Integer(), nullable=True),
    sa.Column('staff_seminar_attend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idp_item_id'], ['idp_items.id'], ),
    sa.ForeignKeyConstraint(['staff_seminar_attend_id'], ['staff_seminar_attends.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idp_item_seminar_attend_assoc')
    # ### end Alembic commands ###
