"""Added sheet column in ServiceLab and ServiceSubLab model

Revision ID: b3aba8d61d50
Revises: 5d8899132e26
Create Date: 2024-12-16 08:48:12.684622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3aba8d61d50'
down_revision = '5d8899132e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet', sa.String(), nullable=True))

    with op.batch_alter_table('service_sub_labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_sub_labs', schema=None) as batch_op:
        batch_op.drop_column('sheet')

    with op.batch_alter_table('service_labs', schema=None) as batch_op:
        batch_op.drop_column('sheet')
    # ### end Alembic commands ###
