"""Added ServiceCustomerQuotationAddress model

Revision ID: b5cd61e62a22
Revises: 68d66f691d2d
Create Date: 2024-11-20 09:10:04.566471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5cd61e62a22'
down_revision = '68d66f691d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_customer_quotation_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('bill_name', sa.String(), nullable=True),
    sa.Column('taxpayer_identification_no', sa.String(), nullable=True),
    sa.Column('quotation_address', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['service_customer_infos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_customer_quotation_addresses')
    # ### end Alembic commands ###
