"""Added ServiceSequenceQuotationID model

Revision ID: b5efda1e4b0d
Revises: d63d6ea99ec6
Create Date: 2025-06-18 09:38:53.155195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5efda1e4b0d'
down_revision = 'd63d6ea99ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_sequence_quotation_ids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('quotation', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_sequence_quotation_ids')
    # ### end Alembic commands ###
