"""Removed address in ElectronicReceiptDetail model

Revision ID: b68f6ab6bedb
Revises: 37d31d5ab3ce
Create Date: 2023-07-11 20:54:04.875611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68f6ab6bedb'
down_revision = '37d31d5ab3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronic_receipt_details', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronic_receipt_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))


    # ### end Alembic commands ###
