"""created subordinate_account_id column in pa_committees table

Revision ID: b713d97a7676
Revises: fda327b9fcdd
Create Date: 2023-07-13 14:42:49.012740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b713d97a7676'
down_revision = 'fda327b9fcdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_committees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subordinate_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('pa_committees_subordinate_account_id_fkey',
                                    'staff_account', ['subordinate_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_committees', schema=None) as batch_op:
        batch_op.drop_constraint('pa_committees_subordinate_account_id_fkey',
                                 type_='foreignkey')
        batch_op.drop_column('subordinate_account_id')

    # ### end Alembic commands ###
