"""Added is_completed column in ServiceRequest model

Revision ID: b82d38d3d3a3
Revises: b2c4d922010e
Create Date: 2025-11-19 11:04:32.665325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b82d38d3d3a3'
down_revision = 'b2c4d922010e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('is_completed')
    # ### end Alembic commands ###
