"""Deleted convenient_time column in ServiceSubLab model

Revision ID: b99ab6fd7f3b
Revises: 45369c675fb2
Create Date: 2025-07-29 22:00:53.332599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b99ab6fd7f3b'
down_revision = '45369c675fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_sub_labs', schema=None) as batch_op:
        batch_op.drop_column('convenient_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_sub_labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('convenient_time', postgresql.TIME(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
