"""Deleted creator_id and creator columns in ServiceResultItem model

Revision ID: b9a855ad9d1e
Revises: 1df8828169c5
Create Date: 2025-11-26 14:33:24.209963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9a855ad9d1e'
down_revision = '1df8828169c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_result_items', schema=None) as batch_op:
        batch_op.drop_constraint('service_result_items_creator_id_fkey', type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_result_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('service_result_items_creator_id_fkey', 'staff_account', ['creator_id'], ['id'])
    # ### end Alembic commands ###
