"""Added organization_type_id and organization_type column in ServiceOrganizationType model

Revision ID: b9d9e2374dff
Revises: 8428910519be
Create Date: 2024-11-14 08:59:12.445396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9d9e2374dff'
down_revision = '8428910519be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_infos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'service_organization_types', ['organization_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_customer_infos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_type_id')
    # ### end Alembic commands ###
