"""added dept ID field to the customer model with a relationship to the department model

Revision ID: ba74f681cdfa
Revises: 4432fb850b64
Create Date: 2020-01-23 21:44:47.170219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba74f681cdfa'
down_revision = '4432fb850b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comhealth_customers', sa.Column('dept_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comhealth_customers', 'comhealth_department', ['dept_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comhealth_customers', type_='foreignkey')
    op.drop_column('comhealth_customers', 'dept_id')
    # ### end Alembic commands ###
