"""added poll-admin assoc table

Revision ID: bcb9d76afa93
Revises: a3b2eaf4f1a9
Create Date: 2026-02-03 08:59:20.944806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb9d76afa93'
down_revision = 'a3b2eaf4f1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('besttime_poll_admin_assoc_table',
    sa.Column('staff_account_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['besttime_polls.id'], ),
    sa.ForeignKeyConstraint(['staff_account_id'], ['staff_account.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('besttime_poll_admin_assoc_table')
    # ### end Alembic commands ###
