"""added some room models

Revision ID: bec4d3a34785
Revises: 710b73d6f9c5
Create Date: 2018-10-18 03:31:49.038917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec4d3a34785'
down_revision = 'e01c12674e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_room_avails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduler_room_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduler_room_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=16), nullable=True),
    sa.Column('number', sa.String(length=16), nullable=True),
    sa.Column('occupancy', sa.Integer(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('business_hour_start', sa.Time(), nullable=True),
    sa.Column('business_hour_end', sa.Time(), nullable=True),
    sa.Column('availability_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['availability_id'], ['scheduler_room_avails.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['scheduler_room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_room_resources')
    op.drop_table('scheduler_room_types')
    op.drop_table('scheduler_room_avails')
    # ### end Alembic commands ###
