"""moved format field to the session model

Revision ID: c25f850d64b2
Revises: 98012dbea0f0
Create Date: 2022-10-29 14:34:15.860435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25f850d64b2'
down_revision = '98012dbea0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eduqa_course_session_details', 'format')
    op.add_column('eduqa_course_sessions', sa.Column('format', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eduqa_course_sessions', 'format')
    op.add_column('eduqa_course_session_details', sa.Column('format', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
