"""Added is_head column in ServiceAdmin model

Revision ID: c2b97ee5f1d6
Revises: d4b868000e10
Create Date: 2025-01-21 13:28:50.160245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2b97ee5f1d6'
down_revision = 'd4b868000e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_head', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_admins', schema=None) as batch_op:
        batch_op.drop_column('is_head')
    # ### end Alembic commands ###
