"""Removed unique procurement_no in ProcurementDetail model

Revision ID: c2bff262e1cf
Revises: 4692495bfe4d
Create Date: 2022-10-28 13:01:34.025000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bff262e1cf'
down_revision = '4692495bfe4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'procurement_details_procurement_no_key', 'procurement_details', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'procurement_details_procurement_no_key', 'procurement_details', ['procurement_no'])
    # ### end Alembic commands ###
