"""Added category column in ServiceResultItem model

Revision ID: c33a25c894e9
Revises: 947b06b4ccae
Create Date: 2026-07-14 09:45:49.593060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c33a25c894e9'
down_revision = '947b06b4ccae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_result_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_result_items', schema=None) as batch_op:
        batch_op.drop_column('category')
    # ### end Alembic commands ###
