"""Added is_central_admin column in ServiceAdmin model

Revision ID: c50e82163762
Revises: 397ea6c5eac0
Create Date: 2025-02-03 09:39:29.552338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c50e82163762'
down_revision = '397ea6c5eac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_central_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_admins', schema=None) as batch_op:
        batch_op.drop_column('is_central_admin')
    # ### end Alembic commands ###
