"""Deleted ServiceCustomerQuotationAddress model

Revision ID: c5499258ca2f
Revises: f138f4da4ed5
Create Date: 2025-02-05 10:55:07.079552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5499258ca2f'
down_revision = 'f138f4da4ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_customer_quotation_addresses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_customer_quotation_addresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bill_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('taxpayer_identification_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quotation_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remark', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['service_customer_infos.id'], name='service_customer_quotation_addresses_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_customer_quotation_addresses_pkey')
    )
    # ### end Alembic commands ###
