"""Added phase column, start column and end column in SoftwareIssues model

Revision ID: c65694b4f2e0
Revises: 80096702a440
Create Date: 2026-04-24 14:55:43.974464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65694b4f2e0'
down_revision = '80096702a440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_issues', schema=None) as batch_op:
        batch_op.drop_column('end')
        batch_op.drop_column('start')
        batch_op.drop_column('phase')
    # ### end Alembic commands ###
