"""Added reason column and other column in ServiceReason model

Revision ID: c66fc7a5f92e
Revises: ac600c0ac6b5
Create Date: 2025-11-19 09:43:28.871937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c66fc7a5f92e'
down_revision = 'ac600c0ac6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('other', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotations', schema=None) as batch_op:
        batch_op.drop_column('other')
        batch_op.drop_column('reason')
    # ### end Alembic commands ###
