"""Added creator_id, creator, sent_at, sender_id and sender columns in ServiceResultItem model

Revision ID: c6c8e95487c8
Revises: b9a855ad9d1e
Create Date: 2025-11-26 14:37:22.962528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6c8e95487c8'
down_revision = 'b9a855ad9d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_result_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff_account', ['creator_id'], ['id'])
        batch_op.create_foreign_key(None, 'staff_account', ['sender_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_result_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('sent_at')
    # ### end Alembic commands ###
