"""added new columns announce_at, start_datetime in table ot_payment_announce

Revision ID: c7028e279d51
Revises: ddfe2c24bd64
Create Date: 2021-11-02 14:06:50.964639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7028e279d51'
down_revision = 'ddfe2c24bd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ot_payment_announce', sa.Column('announce_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ot_payment_announce', sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ot_payment_announce', 'start_datetime')
    op.drop_column('ot_payment_announce', 'announce_at')
    # ### end Alembic commands ###
