"""Added unit_price and total_price columns in ServiceQuotation model

Revision ID: c76de305ca7b
Revises: 273000ea6dbc
Create Date: 2025-07-20 17:52:27.647760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c76de305ca7b'
down_revision = '273000ea6dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotation_items', schema=None) as batch_op:
        batch_op.drop_column('total_price')
        batch_op.drop_column('unit_price')
    # ### end Alembic commands ###
