"""Added relationship gl and gl id column in ElectronicReceiptItem model

Revision ID: c839d3abec54
Revises: 4aeec1c6dd64
Create Date: 2022-11-19 19:15:19.401000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c839d3abec54'
down_revision = '4aeec1c6dd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electronic_receipt_gls',
    sa.Column('gl', sa.String(), nullable=False),
    sa.Column('receive_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('gl')
    )
    op.add_column(u'electronic_receipt_items', sa.Column('gl_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'electronic_receipt_items', 'electronic_receipt_gls', ['gl_id'], ['gl'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'electronic_receipt_items', type_='foreignkey')
    op.drop_column(u'electronic_receipt_items', 'gl_id')
    op.drop_table('electronic_receipt_gls')
    # ### end Alembic commands ###
