"""Added receipt_date and mhesi_no_date columns in ComplaintRepairApproval model

Revision ID: cacdc411a87e
Revises: 473d63ad8f60
Create Date: 2025-06-30 16:07:13.302062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cacdc411a87e'
down_revision = '473d63ad8f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mhesi_no_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.drop_column('receipt_date')
        batch_op.drop_column('mhesi_no_date')
    # ### end Alembic commands ###
