"""add comhealth consent record

Revision ID: cb54b1cc184c
Revises: 258262dfaddf
Create Date: 2022-06-26 21:20:19.933000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb54b1cc184c'
down_revision = '258262dfaddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comhealth_consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('is_consent_given', sa.Boolean(), nullable=True),
    sa.Column('detail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['staff_account.id'], ),
    sa.ForeignKeyConstraint(['detail_id'], ['comhealth_consent_details.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['comhealth_test_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comhealth_consent_records')
    # ### end Alembic commands ###
