"""Added detail column in ServiceLab model

Revision ID: ccf69e27e5b4
Revises: 354b73e3a059
Create Date: 2025-08-04 09:52:54.439523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccf69e27e5b4'
down_revision = '354b73e3a059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_labs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_labs', schema=None) as batch_op:
        batch_op.drop_column('detail')
    # ### end Alembic commands ###
