"""Added admin_status_colo and customer_status_color columns in ServiceStatus model

Revision ID: cd1f657bc329
Revises: 622227a489a8
Create Date: 2025-08-14 11:16:36.065443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd1f657bc329'
down_revision = '622227a489a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_status_color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('customer_status_color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_statuses', schema=None) as batch_op:
        batch_op.drop_column('customer_status_color')
        batch_op.drop_column('admin_status_color')
    # ### end Alembic commands ###
