"""Edited id column in ComplaintCommittee model

Revision ID: cd5f35b8e8db
Revises: cc07fd50bbc4
Create Date: 2025-07-04 15:32:06.222805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd5f35b8e8db'
down_revision = 'cc07fd50bbc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
