"""Added ServiceAppointmentTimeSlot model

Revision ID: cde20fcedb9c
Revises: f960674e8267
Create Date: 2025-12-24 14:16:36.930178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cde20fcedb9c'
down_revision = 'f960674e8267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_appointment_time_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_appointment_time_slots')
    # ### end Alembic commands ###
