"""Deleted lab column in ServiceRequest model

Revision ID: ce2929ee6376
Revises: 644adcb896f2
Create Date: 2026-02-02 09:36:37.636051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce2929ee6376'
down_revision = '644adcb896f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('lab')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
