"""added strategy activity and staff account association table

Revision ID: cfb8052ac8c2
Revises: d10375e557de
Create Date: 2024-01-17 05:17:19.579648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb8052ac8c2'
down_revision = 'd10375e557de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_activity_staff_assoc',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('strategy_activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_account.id'], ),
    sa.ForeignKeyConstraint(['strategy_activity_id'], ['strategy_activities.id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'strategy_activity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_activity_staff_assoc')
    # ### end Alembic commands ###
