"""Added slip, customer_id, admin_id, admin, customer and amount_paid columns in ServicePayment model

Revision ID: cfe96f617040
Revises: 9b0ac44d455d
Create Date: 2025-08-21 10:42:01.707090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfe96f617040'
down_revision = '9b0ac44d455d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('slip', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_payments', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('sent_at')
        batch_op.drop_column('slip')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('payment_type')
    # ### end Alembic commands ###
