"""Deleted phase column in SoftwareIssues model

Revision ID: d0b8cd8c103b
Revises: ee5f5eb2f860
Create Date: 2026-04-24 16:02:14.180552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b8cd8c103b'
down_revision = 'ee5f5eb2f860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_issues', schema=None) as batch_op:
        batch_op.drop_column('phase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
