"""deleted org_kpi_id column in PAItem table

Revision ID: d1512f0ba7a9
Revises: 4de4128f3767
Create Date: 2024-01-11 14:45:56.950384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1512f0ba7a9'
down_revision = '4de4128f3767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_items', schema=None) as batch_op:
        batch_op.drop_constraint('pa_items_org_kpi_id_fkey', type_='foreignkey')
        batch_op.drop_column('org_kpi_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_kpi_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pa_items_org_kpi_id_fkey', 'kpis', ['org_kpi_id'], ['id'])

    # ### end Alembic commands ###
