"""Added remark column, cancelled_at column and reviewd_at column in ComplaintRepairApproval model

Revision ID: d268223c263d
Revises: 976459b74ede
Create Date: 2026-05-08 13:34:28.333733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd268223c263d'
down_revision = '976459b74ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_repair_approvals', schema=None) as batch_op:
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('cancelled_at')
    # ### end Alembic commands ###
