"""created new column in table ot_record (created_at)

Revision ID: d28af20f3d1c
Revises: 08d06f3c1262
Create Date: 2021-12-07 23:20:38.679859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28af20f3d1c'
down_revision = '08d06f3c1262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ot_record', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ot_record', 'created_at')
    # ### end Alembic commands ###
