"""Added order_id column in Province model, District model and Subdistrict model

Revision ID: d2a19f2e29f7
Revises: da2c88aaa94c
Create Date: 2026-01-20 13:51:22.549006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2a19f2e29f7'
down_revision = 'da2c88aaa94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('subdistricts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subdistricts', schema=None) as batch_op:
        batch_op.drop_column('order_id')

    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.drop_column('order_id')

    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_column('order_id')
    # ### end Alembic commands ###
