"""add is_verified to member

Revision ID: d3c8fa44163a
Revises: 89d0ab161e00
Create Date: 2025-08-26 16:20:22.797049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3c8fa44163a'
down_revision = '89d0ab161e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false(), comment='ยืนยันอีเมลแล้ว'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    
    # ### end Alembic commands ###
