"""Deleted approver_comment column in SoftwareRequestDetail model

Revision ID: d56e78a40b40
Revises: 24c74fe18949
Create Date: 2025-04-09 09:57:09.108016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd56e78a40b40'
down_revision = '24c74fe18949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_details', schema=None) as batch_op:
        batch_op.drop_column('approve_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approve_comment', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
