"""added foreign key to the zoom account model

Revision ID: d581c4ce88fa
Revises: 33fe086c0a14
Create Date: 2020-03-31 16:23:26.265388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd581c4ce88fa'
down_revision = '33fe086c0a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smartclass_scheduler_resource_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'smartclass_scheduler_zoom_accounts', sa.Column('resource_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'smartclass_scheduler_zoom_accounts', 'smartclass_scheduler_resource_types', ['resource_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'smartclass_scheduler_zoom_accounts', type_='foreignkey')
    op.drop_column(u'smartclass_scheduler_zoom_accounts', 'resource_type_id')
    op.drop_table('smartclass_scheduler_resource_types')
    # ### end Alembic commands ###
