"""created PAKPIIItemJobPosition table

Revision ID: d5d795128395
Revises: 7723ba2be6be
Create Date: 2023-12-22 18:05:09.820632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d795128395'
down_revision = '7723ba2be6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pa_kpi_item_job_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('job_kpi_id', sa.Integer(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_kpi_id'], ['pa_kpi_job_positions.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['pa_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pa_kpi_item_job_positions')
    # ### end Alembic commands ###
