"""Added sequence column in ServiceQuotationItem and ServiceInvoiceItem models

Revision ID: d63d6ea99ec6
Revises: 0fdeb929b95f
Create Date: 2025-06-18 08:48:41.273841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd63d6ea99ec6'
down_revision = '0fdeb929b95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.String(), nullable=True))

    with op.batch_alter_table('service_quotation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_quotation_items', schema=None) as batch_op:
        batch_op.drop_column('sequence')

    with op.batch_alter_table('service_invoice_items', schema=None) as batch_op:
        batch_op.drop_column('sequence')
    # ### end Alembic commands ###
