"""created ot_record_approval table in OT folder

Revision ID: d8bba556c410
Revises: 3ed8c023e0d2
Create Date: 2022-03-20 18:09:21.241551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bba556c410'
down_revision = '3ed8c023e0d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ot_record_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('approval_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_by_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approval_by_account_id'], ['staff_account.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['ot_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ot_record_approval')
    # ### end Alembic commands ###
