"""created new table ot_compensation_rate into OT folder

Revision ID: d90002fb54e4
Revises: 4ed37e2ff872
Create Date: 2021-11-02 10:52:22.771236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd90002fb54e4'
down_revision = '4ed37e2ff872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ot_compensation_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announce_id', sa.Integer(), nullable=True),
    sa.Column('work_at_org_id', sa.Integer(), nullable=True),
    sa.Column('work_for_org_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('per_period', sa.Integer(), nullable=True),
    sa.Column('per_hour', sa.Integer(), nullable=True),
    sa.Column('per_day', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_faculty_emp', sa.Boolean(), nullable=True),
    sa.Column('is_workday', sa.Boolean(), nullable=False),
    sa.Column('max_hour', sa.Integer(), nullable=True),
    sa.Column('double_payment', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['announce_id'], ['ot_payment_announce.id'], ),
    sa.ForeignKeyConstraint(['work_at_org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['work_for_org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ot_compensation_rate')
    # ### end Alembic commands ###
