"""created new staff_shift_role table in Staff folder

Revision ID: da8b537ba48a
Revises: d7b84b10d569
Create Date: 2022-03-15 17:44:57.288179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8b537ba48a'
down_revision = 'd7b84b10d569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_shift_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('orgs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orgs_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_shift_role')
    # ### end Alembic commands ###
