"""Added position column in StaffPersoalInfo model

Revision ID: dbd518bf3d6b
Revises: 950c75b28e59
Create Date: 2022-11-16 10:02:58.613000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd518bf3d6b'
down_revision = '950c75b28e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_personal_info', sa.Column('position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_personal_info', 'position')
    # ### end Alembic commands ###
