"""Changed type float to string in ProcurementDetail model

Revision ID: de2ef2c1df92
Revises: 21824e284076
Create Date: 2023-07-04 09:50:57.421347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de2ef2c1df92'
down_revision = '21824e284076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procurement_details', schema=None) as batch_op:
        batch_op.alter_column('curr_acq_value',
                              existing_type=postgresql.DOUBLE_PRECISION(precision=53),
                              type_=sa.String(),
                              existing_nullable=True
                              )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procurement_details', schema=None) as batch_op:
        batch_op.alter_column('curr_acq_value',
                              existing_type=sa.String(),
                              type_=postgresql.DOUBLE_PRECISION(precision=53),
                              existing_nullable=True,
                              postgresql_using='curr_acq_value::double precision'
                              )

    # ### end Alembic commands ###
