"""Added approved_at column in ServiceInvoice model

Revision ID: de6d3c3f6d07
Revises: 3ce9ff80ed40
Create Date: 2025-07-16 20:34:24.686464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de6d3c3f6d07'
down_revision = '3ce9ff80ed40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoices', schema=None) as batch_op:
        batch_op.drop_column('approved_at')
    # ### end Alembic commands ###
