"""added is_kpi column in dashboard table

Revision ID: df4d0fbb38dd
Revises: c5347d5d3e2e
Create Date: 2025-11-11 13:05:39.846628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df4d0fbb38dd'
down_revision = 'c5347d5d3e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_kpi', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_column('is_kpi')
    # ### end Alembic commands ###
