"""created committee_id in pa_score_sheets table

Revision ID: df9375f0daac
Revises: 6de5c294a1e7
Create Date: 2023-06-19 11:28:27.974588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9375f0daac'
down_revision = '6de5c294a1e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_score_sheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('committee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pa_committees', ['committee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_score_sheets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('committee_id')

    # ### end Alembic commands ###
