"""added PARound and PAAgreement model

Revision ID: e2a386a59bb1
Revises: 84618dcbfd9e
Create Date: 2023-06-13 14:46:37.662579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a386a59bb1'
down_revision = '84618dcbfd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pa_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pa_agreements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['pa_rounds.id'], ),
    sa.ForeignKeyConstraint(['staff_account_id'], ['staff_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pa_agreements')
    op.drop_table('pa_rounds')
    # ### end Alembic commands ###
