"""Deleted StaffCustomerInfo model and deleted customer_info_info, customer_info column in StaffAaccount model

Revision ID: e30e8d11f046
Revises: db9b11a0ba27
Create Date: 2024-04-30 13:57:17.144599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30e8d11f046'
down_revision = 'db9b11a0ba27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_account', schema=None) as batch_op:
        batch_op.drop_constraint('staff_account_customer_info_id_fkey', type_='foreignkey')
        batch_op.drop_column('customer_info_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_info_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('staff_account_customer_info_id_fkey', 'staff_customer_info', ['customer_info_id'], ['id'])
    # ### end Alembic commands ###
