"""Added SoftwareRequestTestResult model in software_request models

Revision ID: e3dc369f4b03
Revises: 20b6738d155e
Create Date: 2026-04-03 10:25:44.491458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3dc369f4b03'
down_revision = '20b6738d155e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software_request_test_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('updater_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['staff_account.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['software_request_details.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['staff_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('software_request_test_results')
    # ### end Alembic commands ###
