"""added a health education video model

Revision ID: e4db066c9d32
Revises: 2922559e6044
Create Date: 2026-07-08 09:58:45.391571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4db066c9d32'
down_revision = '2922559e6044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comhealth_health_education_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('youtube_url', sa.Text(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_channel', sa.String(length=255), nullable=True),
    sa.Column('health_topics', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('audience_level', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_embeddable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('notes_internal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comhealth_health_education_videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comhealth_health_education_videos_audience_level'), ['audience_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_comhealth_health_education_videos_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_comhealth_health_education_videos_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_comhealth_health_education_videos_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_comhealth_health_education_videos_youtube_video_id'), ['youtube_video_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comhealth_health_education_videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comhealth_health_education_videos_youtube_video_id'))
        batch_op.drop_index(batch_op.f('ix_comhealth_health_education_videos_title'))
        batch_op.drop_index(batch_op.f('ix_comhealth_health_education_videos_language'))
        batch_op.drop_index(batch_op.f('ix_comhealth_health_education_videos_display_order'))
        batch_op.drop_index(batch_op.f('ix_comhealth_health_education_videos_audience_level'))

    op.drop_table('comhealth_health_education_videos')
    # ### end Alembic commands ###
