"""Deleted sample_appointment_id and sample_appointment column in ServiceRequest model

Revision ID: e5c5c3fc9a1c
Revises: d99e3b890c12
Create Date: 2024-11-20 22:48:37.605945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5c5c3fc9a1c'
down_revision = 'd99e3b890c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_constraint('service_requests_sample_address_id_fkey', type_='foreignkey')
        batch_op.drop_column('sample_address_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('service_requests_sample_address_id_fkey', 'service_sample_appointments', ['sample_address_id'], ['id'])
    # ### end Alembic commands ###
