"""Deleted appointment_date in ServiceSample model

Revision ID: e740f09467cf
Revises: 3f0fcf01bd67
Create Date: 2025-08-22 13:27:30.005521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e740f09467cf'
down_revision = '3f0fcf01bd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_samples', schema=None) as batch_op:
        batch_op.drop_column('appointment_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
