"""Added default in has_licence and has_recipe columns of ServiceSample model

Revision ID: e75a3e619320
Revises: 661ae4987acf
Create Date: 2025-07-19 18:50:19.016232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e75a3e619320'
down_revision = '661ae4987acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
