"""Deleted report_language and hard_copy columns in ServiceRequest model

Revision ID: e769b507597b
Revises: 0bf4ae18dcac
Create Date: 2025-06-12 13:51:10.180323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e769b507597b'
down_revision = '0bf4ae18dcac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('report_language')
        batch_op.drop_column('hard_copy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hard_copy', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('report_language', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
