"""Deleted product column in ServiceRequest model

Revision ID: e7db60de5645
Revises: 0e9d5709853b
Create Date: 2025-02-10 13:47:27.977863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7db60de5645'
down_revision = '0e9d5709853b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
