"""added session role item model

Revision ID: ea2409755ae7
Revises: f6205a994c59
Create Date: 2022-12-07 04:39:46.994421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2409755ae7'
down_revision = 'f6205a994c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eduqa_course_session_detail_role_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'eduqa_course_session_detail_roles', sa.Column('role_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'eduqa_course_session_detail_roles', 'eduqa_course_session_detail_role_items', ['role_item_id'], ['id'])
    op.drop_column(u'eduqa_course_session_detail_roles', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'eduqa_course_session_detail_roles', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'eduqa_course_session_detail_roles', type_='foreignkey')
    op.drop_column(u'eduqa_course_session_detail_roles', 'role_item_id')
    op.drop_table('eduqa_course_session_detail_role_items')
    # ### end Alembic commands ###
