"""added color field

Revision ID: eb983d0e18b8
Revises: cfb8052ac8c2
Create Date: 2024-01-17 17:02:47.249706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb983d0e18b8'
down_revision = 'cfb8052ac8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduler_room_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduler_room_types', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
