"""created new column named closed_at in StaffSeminar table

Revision ID: ef5bec63e536
Revises: 0ee9897aceb7
Create Date: 2024-07-03 08:38:29.666798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5bec63e536'
down_revision = '0ee9897aceb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_seminar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_seminar', schema=None) as batch_op:
        batch_op.drop_column('closed_at')

    # ### end Alembic commands ###
