"""Added recorded_at column, recorder_id column and recorder column in SoftwareRequestTestResult model

Revision ID: efd218f6b8f2
Revises: 1c5180729bee
Create Date: 2026-04-28 09:48:35.382211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd218f6b8f2'
down_revision = '1c5180729bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_test_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('recorder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff_account', ['recorder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software_request_test_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recorder_id')
        batch_op.drop_column('recorded_at')
    # ### end Alembic commands ###
