"""added title field to the health person model

Revision ID: efde7dbb96de
Revises: 6c89ec739fa3
Create Date: 2018-03-22 16:17:12.395984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efde7dbb96de'
down_revision = '6c89ec739fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_health_person', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_health_person', 'title')
    # ### end Alembic commands ###
