"""added close datetime field

Revision ID: f2293f43fe82
Revises: 3fc7cd4c9b56
Create Date: 2024-06-10 10:08:36.402889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2293f43fe82'
down_revision = '3fc7cd4c9b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.drop_column('closed_at')

    # ### end Alembic commands ###
