"""Deleted activity on PurchaseTrackerStatus Model

Revision ID: f22faa5d8815
Revises: 957421d47846
Create Date: 2021-12-16 22:20:47.503000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22faa5d8815'
down_revision = '957421d47846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker_statuses', 'activity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_statuses', sa.Column('activity', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
