"""added number field to PLO model

Revision ID: f29938a471de
Revises: d69322ccb719
Create Date: 2023-10-18 10:36:16.365969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29938a471de'
down_revision = 'd69322ccb719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eduqa_plos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eduqa_plos', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###
