"""Updated account_status in PurchaseTrackerAccount

Revision ID: f3e1b7ecd415
Revises: 4ae44897c047
Create Date: 2022-04-07 23:37:00.211000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e1b7ecd415'
down_revision = '4ae44897c047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_accounts', sa.Column('cancelled_datetime', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('tracker_accounts', 'account_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_accounts', sa.Column('account_status', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('tracker_accounts', 'cancelled_datetime')
    # ### end Alembic commands ###
