"""Added sample_integrity column in ServiceSample model

Revision ID: f4937e0047d6
Revises: cfa306539abb
Create Date: 2025-07-08 23:12:32.777946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4937e0047d6'
down_revision = 'cfa306539abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_integrity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_samples', schema=None) as batch_op:
        batch_op.drop_column('sample_integrity')
    # ### end Alembic commands ###
