"""created StaffLeaveRemainQuota table

Revision ID: f4ad2ec4ef04
Revises: a2829be91fb8
Create Date: 2020-06-23 16:21:42.224056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ad2ec4ef04'
down_revision = 'a2829be91fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_leave_remain_quota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_account_id', sa.Integer(), nullable=True),
    sa.Column('last_year_quota', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_account_id'], ['staff_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_leave_remain_quota')
    # ### end Alembic commands ###
