"""added inform_score_at column in pa_score_sheets table

Revision ID: f65c8ec075ac
Revises: 5542146bff0e
Create Date: 2023-08-17 15:59:44.015101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65c8ec075ac'
down_revision = '5542146bff0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_score_sheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inform_score_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_score_sheets', schema=None) as batch_op:
        batch_op.drop_column('inform_score_at')

    # ### end Alembic commands ###
