"""deleted column attend_online in table staff_seminar

Revision ID: f6a173159dac
Revises: d70d628728d2
Create Date: 2021-05-27 17:08:08.881952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a173159dac'
down_revision = 'd70d628728d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_seminar', 'attend_online')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_seminar', sa.Column('attend_online', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
