"""added core competency item and core competency score sheet item models

Revision ID: f77771201831
Revises: 2c070188cf09
Create Date: 2023-06-23 13:30:07.996073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77771201831'
down_revision = '2c070188cf09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pa_core_competency_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scoresheet_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['scoresheet_id'], ['pa_score_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pa_core_competency_score_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score_sheet_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['pa_core_competency_items.id'], ),
    sa.ForeignKeyConstraint(['score_sheet_id'], ['pa_score_sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pa_core_competency_score_items')
    op.drop_table('pa_core_competency_items')
    # ### end Alembic commands ###
