"""added is_closed column in PAFunctionalCompetencyRound table

Revision ID: f7b5b69d4b81
Revises: 41ef5682f91b
Create Date: 2023-11-21 16:51:22.177488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b5b69d4b81'
down_revision = '41ef5682f91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_functional_competency_round', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pa_functional_competency_round', schema=None) as batch_op:
        batch_op.drop_column('is_closed')

    # ### end Alembic commands ###
