"""Deleted total_price column in ServiceInvoice model

Revision ID: f8679bc1c5bb
Revises: 901e932a46f2
Create Date: 2025-07-20 17:30:15.612587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8679bc1c5bb'
down_revision = '901e932a46f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoices', schema=None) as batch_op:
        batch_op.drop_column('total_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
