"""added position to the cashier field

Revision ID: f907b267aae0
Revises: 0173c0f635b9
Create Date: 2019-12-03 05:10:16.785586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f907b267aae0'
down_revision = '0173c0f635b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comhealth_cashier', sa.Column('position', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comhealth_cashier', 'position')
    # ### end Alembic commands ###
