"""Added cost_center_id column, cost_center column, io_code_id column, io_code column, product_code_id column and product_code column in ComplaintRecord model

Revision ID: f9705c26f801
Revises: 88137613850a
Create Date: 2026-04-07 08:58:57.514392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9705c26f801'
down_revision = '88137613850a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_center_id', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('io_code_id', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('product_code_id', sa.String(length=12), nullable=True))
        batch_op.create_foreign_key(None, 'cost_centers', ['cost_center_id'], ['id'])
        batch_op.create_foreign_key(None, 'iocodes', ['io_code_id'], ['id'])
        batch_op.create_foreign_key(None, 'product_codes', ['product_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_code_id')
        batch_op.drop_column('io_code_id')
        batch_op.drop_column('cost_center_id')
    # ### end Alembic commands ###
