"""added models for docs query app

Revision ID: f9e48eb8988f
Revises: 0a631453b876
Create Date: 2026-07-29 07:09:35.336413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e48eb8988f'
down_revision = '0a631453b876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs_query_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drive_file_id', sa.String(length=255), nullable=False),
    sa.Column('document_title', sa.String(length=512), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('document_type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('extracted_text_key', sa.String(length=1024), nullable=True),
    sa.Column('chunks_key', sa.String(length=1024), nullable=True),
    sa.Column('artifact_key', sa.String(length=1024), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted_char_count', sa.Integer(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=True),
    sa.Column('chunking_method', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_file_id')
    )
    with op.batch_alter_table('docs_query_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docs_query_documents_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docs_query_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docs_query_documents_status'))

    op.drop_table('docs_query_documents')
    # ### end Alembic commands ###
