"""Added pdf_file column in ElectronicReceiptDetail model

Revision ID: fc211f1333e4
Revises: 82b2e016f909
Create Date: 2023-09-06 18:04:36.644265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc211f1333e4'
down_revision = '82b2e016f909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronic_receipt_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_file', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electronic_receipt_details', schema=None) as batch_op:
        batch_op.drop_column('pdf_file')

    # ### end Alembic commands ###
