"""Added status column in ServiceResultItem model

Revision ID: fd5e190c3d45
Revises: 128e46cbb1c8
Create Date: 2025-07-24 11:29:36.556325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd5e190c3d45'
down_revision = '128e46cbb1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_result_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_result_items', schema=None) as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###
