"""Added format service column in ProcurementRequire model

Revision ID: fdc99c0d0781
Revises: 446f5c7c7f69
Create Date: 2023-05-09 13:30:00.548000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc99c0d0781'
down_revision = '446f5c7c7f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_requires', sa.Column('format_service', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procurement_requires', 'format_service')
    # ### end Alembic commands ###
