"""added food_type in staff_seminar_pre_registers table

Revision ID: fe51848fb109
Revises: 7613d0410576
Create Date: 2025-04-08 16:16:25.066416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe51848fb109'
down_revision = '7613d0410576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_seminar_pre_registers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_seminar_pre_registers', schema=None) as batch_op:
        batch_op.drop_column('food_type')
    # ### end Alembic commands ###
