"""added some more fields to the chem items table

Revision ID: ff28e97be42f
Revises: 9eefd1464ce1
Create Date: 2019-01-29 16:04:33.013595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff28e97be42f'
down_revision = '9eefd1464ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemdb_items', sa.Column('created_at', sa.Date(), server_default=sa.text(u'now()'), nullable=True))
    op.add_column('chemdb_items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemdb_items', 'updated_at')
    op.drop_column('chemdb_items', 'created_at')
    # ### end Alembic commands ###
